### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#1]
Create a mechanism for attaching and checking scoped access tokens.

For example:

    def get_scopes():
        return [
            'read:messages',
            'write:messages',
        ]

**Comment by nullpixel** [comment]
This would be very cool!

**Comment by ahopkins** [comment]
Thanks. I am going to be working on another batch of upgrades to this (hopefully this week). This is the next thing I am thinking of adding. Any particular thoughts certainly welcome.

**Comment by nullpixel** [comment]
Will let you know. This lib is quite useful for me, so I may contribute to some of the stuff on your roadmap

**Comment by ahopkins** [comment]
@nullpixel Awesome. Would love to see it.

**Comment by ahopkins** [comment]
There is a new branch `scopes`.

https://github.com/ahopkins/sanic-jwt/tree/scopes#scopes

Seems to be working as expected. But, before merging into `master` I am going to add my test suite.
