### ISSUE TITLE
Object user can't be used in 'await' expression 

### ISSUE THREAD

**Issue by stefanm8** [ahopkins/sanic-jwt#10]
Using the code from the documentation : 

`
def authenticate(request, *args, **kwargs):
    username = request.json.get('username', None)
    password = request.json.get('password', None)

    if not username or not password:
        raise exceptions.AuthenticationFailed("Missing username or password.")

    user = username_table.get(username, None)
    if user is None:
        raise exceptions.AuthenticationFailed("User not found.")

    if password != user.password:
        raise exceptions.AuthenticationFailed("Password is incorrect.")

    return user
`

I get an internal server error while trying to get a access_token with the following command
`curl -d '{"username":"user1","password":"abcxyz"}' 127.0.0.1:8000/auth`

the error I get is
`
2017-10-19 14:26:05 - (network)[INFO][127.0.0.1:46704]: POST http://127.0.0.1:8000/auth  500 144
2017-10-19 14:26:08 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/home/noone/Development/Projects/PushGroupBackEnd/env/lib/python3.5/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/home/noone/Development/Projects/PushGroupBackEnd/env/lib/python3.5/site-packages/sanic_jwt/blueprint.py", line 21, in authenticate
    raise e
  File "/home/noone/Development/Projects/PushGroupBackEnd/env/lib/python3.5/site-packages/sanic_jwt/blueprint.py", line 19, in authenticate
    user = await request.app.auth.authenticate(request, *args, **kwargs)
TypeError: object User can't be used in 'await' expression
`

**Comment by ahopkins** [comment]
Thanks @stefanm8. It is a problem with the documentation. The `authenticate` method needs to be a coroutine.

    async def authenticate(request, *args, **kwargs):
        ...

So, the FULL basic version that gets you up and running is here:

```python
from sanic import Sanic
from sanic_jwt import exceptions
from sanic_jwt import initialize


class User(object):
    def __init__(self, id, username, password):
        self.user_id = id
        self.username = username
        self.password = password

    def __str__(self):
        return "User(id='%s')" % self.id


users = [
    User(1, 'user1', 'abcxyz'),
    User(2, 'user2', 'abcxyz'),
]

username_table = {u.username: u for u in users}
userid_table = {u.user_id: u for u in users}


async def authenticate(request, *args, **kwargs):
    username = request.json.get('username', None)
    password = request.json.get('password', None)

    if not username or not password:
        raise exceptions.AuthenticationFailed("Missing username or password.")

    user = username_table.get(username, None)
    if user is None:
        raise exceptions.AuthenticationFailed("User not found.")

    if password != user.password:
        raise exceptions.AuthenticationFailed("Password is incorrect.")

    return user


app = Sanic()
initialize(
    app,
    authenticate=authenticate,
)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000)
```

I will add this to the `./example` folder
