### ISSUE TITLE
response_class isn't referenced in code

### ISSUE THREAD

**Issue by taybin** [ahopkins/sanic-jwt#105]
In the documentation, it is stated that responses can by modified by subclassing Responses and overriding some methods, and then setting `response_class=MyReponses` in the Initialize() function.

The source doesn't reference response_class though.  My Responses subclass doesn't appear to be called.

**Comment by taybin** [comment]
The source code uses `responses_class`, not `response_class`.

**Comment by vltr** [comment]
> The source code uses `responses_class`, not `response_class`.

Yeap, this is a typo, sorry for the inconvenience. It'll be fixed in the next release :+1:

**Comment by ahopkins** [comment]
This has been corrected in the docs ready for 1.1
