### ISSUE TITLE
Failed to access refresh endpoint

### ISSUE THREAD

**Issue by Jeffwhen** [ahopkins/sanic-jwt#106]
Got a 403 `Authentication Failed` exception. Should I implement refresh token check in my `authenticate` handler? Or it seems to me there's no where to check the validation of refresh request.

Update
======
My store strategy is wrong.

**Comment by ahopkins** [comment]
@Jeffwhen Glad you were able to figure out what happened. In the future, I would be happy to help diagnose any other problems you have.
