### ISSUE TITLE
Register example from documentation is not up to date

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#111]
Hi,

How to create a register view with the latest sanic-jwt version?

the example provided here: https://sanic-jwt.readthedocs.io/en/latest/pages/endpoints.html?highlight=register#custom-endpoints is not up to date.

Thanks!

**Comment by vltr** [comment]
Hello, @gbnk0 !

What was your test, exactly? Since that code is just a snippet, it is incomplete, like there's no configuration for `authenticate`, `refresh_token` and so on. Based on that exactly same snippet and commenting out what would not work (unless setting the proper configuration parameters), I was able to get it working just fine:

```python
from sanic import Sanic
from sanic_jwt import BaseEndpoint, Initialize


class Register(BaseEndpoint):
    async def post(self, request, *args, **kwargs):
        # username = request.json.get('username', None)  # i won't be using it
        # email = request.json.get('email', None)  # i won't be using it

        # helper = MyCustomUserAuthHelper()  # this is just a "presumption"
        # user = helper.register_new_user(username, email)  # this would return
                                                            # a user object or
                                                            # dict, like bellow
        user = {"user_id": 20}

        access_token, output = await self.responses.get_access_token_output(
            request,
            user,
            self.config,
            self.instance)

        # no refresh token configured, so, this won't work at all
        # refresh_token = await self.instance.auth.get_refresh_token(request, user)
        # output.update({
        #     self.config.refresh_token_name: refresh_token
        # })

        response = self.responses.get_token_reponse(
            request,
            access_token,
            output,
            # refresh_token=refresh_token,  # no refresh token
            config=self.config)

        return response


my_views = (
    ('/register', Register),
)


if __name__ == "__main__":
    app = Sanic(__name__)
    Initialize(
        app,
        class_views=my_views,
        authenticate=lambda: True,
        refresh_token=False
    )
    app.run()
```

And calling it using `curl`:

```
$ curl http://127.0.0.1:8000/auth/register -H "Content-Type: application/json" -d '{"something":"here"}'
{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyMCwiZXhwIjoxNTI4OTA5NjYyfQ.80B3nWrdpS1AUzHu8kPNQdBqCNHsmVZpEnn4jZB9rvc"}
```

Please, if you still have any doubts, please, let us know your thoughts :wink:

**Comment by ahopkins** [comment]
@gbnk0 As @vltr mentioned, the documentation is meant to be illustrative. It is highly dependent upon your specific use case. We would (of course) be happy to help you create something. The key points are those that @vltr mentioned.

You want to return the output of `self.responses.get_token_reponse()`.

**Comment by gbnk0** [comment]
Yes exactly, i use the same snippet as you mentioned, but when i get a response, access_token is OK but  the returned refres_token is <sanic_jwt.configuration.ConfigItem object at 0x7f0cfb584ac8>.

I think some functions have changed between version 1.0.2.1 and 1.1.1
My snippet looks like this (thanks to ahopkins):
```python
class Register(BaseEndpoint):
    async def post(self, request, *args, **kwargs):
        response = json(resp_error, status=400)
        request_json = request.json

        email = request_json['email']
        email_valid = email_validator(email)

        if email_valid:

            new_user = {
                "email": email,
                "password": request_json['password'],
                "register_date": datetime.now(pytz.utc),
                "username": "",
                "phone": "",
                "scopes": ['user']
            }

            db_user = db.add_user(**new_user)

            if db_user:

                user = request.app.auth.authenticate(request, *args, **kwargs)
                access_token, output = await self.responses.get_access_token_output(
                    request,
                    user,
                    self.config,
                    self.instance)

                refresh_token = await self.instance.auth.get_refresh_token(request, user)
                output.update({
                    self.config.refresh_token_name: refresh_token
                })

                response = self.responses.get_token_reponse(
                    request,
                    access_token,
                    output,
                    refresh_token=refresh_token,
                    config=self.config)
        else:
            response = json(resp_invalid_email, status=400)

        return response
```
Thanks

**Comment by vltr** [comment]
Hello, @gbnk0 !

I think that the solution here will be an easy one :wink:

One of the major changes to version 1.1 was the fact that the configuration items can be modified at runtime (if a developer wishes to do so, like a user secret and so on) and because of that, accessing the config variables are now function calls instead of direct reference, so:

```python
self.config.refresh_token_name
```

Now becomes:

```python
self.config.refresh_token_name()
```

And everything related to configuration keys follows the same principle. Please, [take a look here](http://sanic-jwt.readthedocs.io/en/latest/pages/changelog.html#version-1-1-2018-06-03) for more information regarding (breaking) changes on version 1.1 and feel free to request any clarification regarding this subject :smiley:

**Comment by vltr** [comment]
Oh, there's also mention to that breaking change in [this section](http://sanic-jwt.readthedocs.io/en/latest/#what-is-new-in-version-1-1) of the docs main page :wink:

**Comment by vltr** [comment]
@gbnk0 no need to say sorry, it was a breaking change in this new version. I'm the one who needs to say sorry for that, since your application that was on-hold for almost a day. I'm really glad that I could help! :wink:

Cheers and a nice day to you too!

**Comment by vltr** [comment]
And **yes**, I just saw now that the referred snippet is outdated! Oh my! :sweat_smile:

**Comment by ahopkins** [comment]
I'm putting together some minor tweaks and will push this documentation change out with v1.1.2
