### ISSUE TITLE
@inject_user() decorator hangs for me

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#114]
Hi i'm back with another issue, i use @inject_user on a route, it give me this message:

> TypeError: object dict can't be used in 'await' expression while handling path /me

Here's my snippet:
```python
@blueprint_me.get("")
@protected()
@inject_user()
async def my_route(request, user):
    return my_func(request, user, es)
```

**Comment by gbnk0** [comment]
ok, i've found a solution, my retrieve_user function was not async

**Comment by vltr** [comment]
Hello, @gbnk0 ! 

Sorry for this late answer, I was not around my computer. AFAIK, _there should not be any problems if_ your `retrieve_user` function is not `async` (as you can see [here](https://github.com/ahopkins/sanic-jwt/blob/dev/sanic_jwt/endpoints.py#L84-L86)). I don't know if you found a hidden bug or something. Would you mind sharing more code with us or reproduce the error with a small snippet?

I'll leave this issue open for @ahopkins knowledge.

Thanks a lot for your time and patience reporting these "misbehavior" with us :muscle: :smiley:

**Comment by ahopkins** [comment]
@gbnk0 and @vltr `retrieve_user` should be able to be either a regular function:

    def my_retrieve_user(...): ...

Or, an awaitable:

    async def my_retrieve_user(...): ...

Furthermore, if it is returning an object, the `to_dict()` method could also be a regular method or an awaitable.

@gbnk0, if you wouldn't mind, can you send me your `Initialize` snippet, and at least a barebones representation of your `retrieve_user` definition?

**Comment by gbnk0** [comment]
Hi,

Here is my (dirty) code snippet:

```python
def retrieve_user(request, payload, *args, **kwargs):
    result = None
    if payload:
        user_id = payload.get('user_id', None)

        if user_id != None:
            user = db.get_user(user_id=user_id)
            # Remove password from returned user
            if type(user) == dict:
                user.pop('password', None)
                result =  user

    return result
```

and the initialize:

```python
initialize(app,
           authenticate,
           store_refresh_token=store_refresh_token,
           retrieve_refresh_token=retrieve_refresh_token,
           retrieve_user=retrieve_user,
           class_views=custom_views,
           add_scopes_to_payload=scope_extender
        )
```

Regards,

**Comment by ahopkins** [comment]
@gbnk0 Thank you!

I found [the bug](https://github.com/ahopkins/sanic-jwt/blob/dev/sanic_jwt/decorators.py#L178).

```python
user = await instance.auth.retrieve_user(request, payload)
```

This should be executed with `utils.call()`, which is our under the hood helper method that allows for either `def` or `async def`.

The line should be:

```python
user = await utils.call(instance.auth.retrieve_user, request, payload)
```

My bad. Thanks for pointing it out.

**Comment by gbnk0** [comment]
Can i inject_user on an entire blueprint?

**Comment by ahopkins** [comment]
The `inject_user` decorator specifically works on routes. If you want it on an entire Blueprint, then I would suggest making a subclass of `HTTPMethodView`. Something like this:

```python
from sanic import Sanic
from sanic.response import text
from sanic.views import HTTPMethodView
from sanic_jwt import inject_user
from sanic import Blueprint


app = Sanic('myapp')
bp = Blueprint('mybp')


class MyBaseHTTPView(HTTPMethodView):
    decorators = [inject_user(), ]

class SomeBPView(MyBaseHTTPView):
  async def get(self, request, user):
      return text(f'Hello {user.username}')

bp.add_route(SomeBPView.as_view(), '/')
app.blueprint(bp)
```

I have not tried this. But, it should look something like this.

**Comment by gbnk0** [comment]
Ok i'll try this, thanks

**Comment by ahopkins** [comment]
This should be resolved in the latest commits.
