### ISSUE TITLE
500 error when using a malformed token

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#116]
Hi,

I get this error:
```
DecodeError: Not enough segments while handling path /me
```
My Auth header: Bearer invalidtokenhduisqhd

When i do a query on /me with an invalid token, is it a feature or a bug?

Thanks,

**Comment by gbnk0** [comment]
I think it should return me a 400 or a 401 ?

**Comment by ahopkins** [comment]
We should probably be catching that, you are right. I should be a `400`.

**Comment by gbnk0** [comment]
Thanks for that

**Comment by ahopkins** [comment]
I want to spend some more time tonight on a few more unit tests. Then I have a few items to update in docs and I will push a new release to pypi. But, at the least you can install from the dev branch if needed.
