### ISSUE TITLE
Disable blueprint or configure blueprint name?

### ISSUE THREAD

**Issue by jiamo** [ahopkins/sanic-jwt#127]
For some reason I need two auth instance in a sanic app. But the name of blueprint was hardcode which can't change and can't disable too.  So there will be a problem. Can we make add blueprint name configureable?

**Comment by ahopkins** [comment]
Sure thing! Do you want to take a swing at a PR? I will likely  not have a chance to get to it until mid week next week.

**Comment by jiamo** [comment]
At now disable may be not fit. I just add simple entry in configure dict and init the bp after load config.

**Comment by ahopkins** [comment]
I have merged the PR. Documentation needs and update and we should add a test before release.

**Comment by jiamo** [comment]
Just for remind. I am not sure my English is good enough to make suitable document or test case.

**Comment by ahopkins** [comment]
No worries. I will handle that part.

**Comment by jiamo** [comment]
I just find a problem. Our init purpose to use two instance of auth. The custom blueprint name can solve start error.  However
```
    def __initialize_instance(self):
        """
        Take any predefined methods/handlers and insert them into Sanic JWT
        """
        config = self.config

        # Initialize instance of the Authentication class
        self.instance.auth = self.authentication_class(self.app, config=config)
```

`self.instance.auth` seem to make the app instance only have one at one time. If I want to use two auth. I need a set a different from `auth`.

**Comment by ahopkins** [comment]
You are initializing on multiple blueprints?

**Comment by jiamo** [comment]
In my case I need support two version auth system.  


    v1.initialize(
        app,
        authenticate,
        store_refresh_token=store_refresh_token,
        retrieve_refresh_token=retrieve_refresh_token,
        retrieve_user=retrieve_user,
        add_scopes_to_payload=scopes_payload,
        extend_payload=payload_extender,
    )

    v2.initialize(
        app,
        authenticate,
        store_refresh_token=store_refresh_token,
        retrieve_refresh_token=retrieve_refresh_token,
        retrieve_user=retrieve_user,
        add_scopes_to_payload=scopes_payload,
        extend_payload=payload_extender,
    )

So I can use like this:

    request.app.auth_v1.generate_refresh_token(
        request, auth_dict)
    request.app.auth_v2.generate_refresh_token(
        request, auth_dict)

Does this mean when initalize app we need set app attr `auth`  a configuralbe name?

**Comment by ahopkins** [comment]
Okay .... I see. Currently, there is no way to attach multiple instances of Sanic JWT to a single instance of Sanic.

As you mentioned, `sanic-jwt` patches either the sanic `app` or `blueprint` to add the `auth` property:

    isinstance(app.auth, sanic_jwt.Authentication)

I think the way to handle this would be for you to initialize on a Blueprint.

[From the docs](https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html#instance):

```
async def authenticate(request, *args, **kwargs):
    return get_my_user()

app = Sanic()
bp1 = Blueprint('my_blueprint_1')
bp2 = Blueprint('my_blueprint_2')

Initialize(app, authenticate=authenticate)
Initialize(bp1, authenticate=authenticate, access_token_name='mytoken')
Initialize(bp2, authenticate=authenticate, access_token_name='yourtoken')
```

You should be able to accomplish the same thing and have URLs as: `/my/path/auth1` and `/my/path/auth2`.

Does this help? For now, I do not plan to add multiple instances of `sanic-jwt` to a single `app` or `blueprint`.

**Comment by jiamo** [comment]
It is helpful. I try to do init on blueprint.
