### ISSUE TITLE
Disabling protection at runtime

### ISSUE THREAD

**Issue by rubik** [ahopkins/sanic-jwt#129]
I have checked the docs but it does not seem that my use case is mentioned, so that's why I'm opening an issue.

We have an API server that is used by our users and needs JWT protection. However, we also have a secondary instance of the API server that runs in our internal network and we would like to disable protection there. The API is otherwise the same. It would be best if this could be done in some dynamic way so that we could still use the same code base and push updates to both versions.

I think that even if this is not supported it can be done by creating a decorator that wraps `protected` in some way, am I correct?

Thanks!

**Comment by rubik** [comment]
From my experiments this works:
```python
import functools
from sanic_jwt.decorators import _do_protection


def custom_protected(initialized_on=None, **kw):
    def _aux(view):
        @functools.wraps(view)
        async def _inner(request, *args, **kwargs):
            if request.app.config.SANIC_JWT_NO_PROTECTION:
                return await view(request, *args, **kwargs)
            kwargs.update({
                'initialized_on': initialized_on,
                'kw': kw,
                'request': request,
                'f': view,
            })
            return await _do_protection(*args, **kwargs)
        return _inner
    return _aux
```

And now I can just start the app by setting `app.config.SANIC_JWT_NO_PROTECTION` with a value from the command line.

Thoughts? Is this something that you think should be added to the library or can it be just added as an example to the documentation?

**Comment by ahopkins** [comment]
Sorry.... I'm now at a computer so I cannot provide a snippet.

there probably is a need for a built in configuration value. And with the new runtime configuration calls (https://sanic-jwt.readthedocs.io/en/latest/pages/configuration.html#configuration-class) this would be a perfect scenario. 

Next week I'll probably be pushing some changes and getting a new release ready. So maybe I'll add this directly into the protected decorator.

**Comment by rubik** [comment]
@ahopkins Thanks a lot, that would be great!

**Comment by ahopkins** [comment]
Sorry for the **ridiculous** delay on this.

I have implemented this and will be pushing it and releasing it soon.

```app = Sanic()

async def authenticate(request, *args, **kwargs):
    return {"user_id": 1}

sanicjwt = Initialize(
    app,
    authenticate=authenticate,
    do_protection=False,
)

@app.route("/protected")
@sanicjwt.protected()
def protected_route(request):
    return json({"protected": "yes"})

_, response = app.test_client.get(
    "/protected"
)

assert response.status == 200
assert response.json.get("protected") == "yes"```

Rather than `SANIC_JWT_NO_PROTECTION`, I opted for the reverse: `SANIC_JWT_DO_PROTECTION`. I think being about to set this to `False` makes it slightly easier to reason. I am closing this as I will be pushing this shortly.

**Comment by rubik** [comment]
@ahopkins Thanks! This is perfect!
