### ISSUE TITLE
Custom JSON response

### ISSUE THREAD

**Issue by nullpixel** [ahopkins/sanic-jwt#13]
Add an ability to change how Sanic JWT responds to endpoints, and authentication failures.

**Comment by ahopkins** [comment]
@nullpixel I have definitely been thinking about the authentication failures bit. For example, I can think of at least three different scenarios that might be desirable:

1. Raise an `Exception`
1. Return JSON with details of the authentication failure (or other exceptions as well)
1. Return JSON without details, and just some generic message about authentication failure

But, what do you mean about "responds to endpoints"?

**Comment by nullpixel** [comment]
Option one seems the most desirable for me, not sure about others though.

Sanic JWT comes with built in endpoints, but they all have set responses, and cannot be overridden as far as I'm aware. Apologies, I should've made the wording clearer.

**Comment by ahopkins** [comment]
Got it. I think that all three have potential uses during both development and production.

As for the second point:

> Sanic JWT comes with built in endpoints, but they all have set responses, and cannot be overridden as far as I'm aware. Apologies, I should've made the wording clearer.

See #14.

**Comment by nullpixel** [comment]
👍

**Comment by ahopkins** [comment]
See PR #58 for implementation of this.

**Comment by ahopkins** [comment]
This has been added and will be added to version 1.0.
