### ISSUE TITLE
403 http status code after token expiration

### ISSUE THREAD

**Issue by python-programmer** [ahopkins/sanic-jwt#131]
First of all, thanks to your great module
I want when a token expired
get 401 status code instead of 403
how to resolve this?

**Comment by ahopkins** [comment]
I've gone back and forth on this question several times coming up with good arguments for both. I'll do another review and see what the consensus is... you probably are right that 401 for expiration makes sense. Thanks for your attention.... I will surely try to get this right.

In the  meantime, have you seen the section on overriding exception responses? https://sanic-jwt.readthedocs.io/en/latest/pages/endpoints.html#exception-handling

**Comment by python-programmer** [comment]
@ahopkins thanks,
if I override response, There will be a problem:
When the token is valid and the user does not have enough permission to use resources.
In this situation, (for resource A) we return 401 status code (instead of 403) to the client and it decides to sign out the user and redirected her to the sign in page, and the user sign in again and he want to access to the resource A, and we return 401 status code (instead of 403) again, The user will be stuck in the loop

**Comment by ahopkins** [comment]
The next release will make this switch.
