### ISSUE TITLE
Question about class views

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#132]
Hi,

I want to implement a "password reset feature" in my app, i think i have to use a custom class_view like in the documentation: https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html#additional-views.

I'm right?
Thanks,

**Comment by ahopkins** [comment]
Makes sense to me. I think that the example you linked to would be a good solution for exactly this feature.

I am working on putting together an article (it may end up being a couple) on a few different types of use cases. Then ultimately, my idea is to release a docker image that could be a real simple way for people to add an authentication service. I started the barebones one here: https://hub.docker.com/r/admhpkns/sanic-jwt/

But, as for your question. Yes, I would suggest copying that code and using that as a start.

**Comment by gbnk0** [comment]
OK, thanks
