### ISSUE TITLE
Fix DeprecationWarning

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#137]
During tests execution, a `DeprecationWarning` is given for `pyjwt` method `decode`:

```
  DeprecationWarning
/home/richard/projects/sanic-jwt/.tox/py37/lib/python3.7/site-packages/jwt/api_jws.py:146: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
```

We have to deal with this in a future release.

**Comment by ahopkins** [comment]
I believe HS256 is the default, so we should stick with that to not break compatibility.

**Comment by ahopkins** [comment]
This is a much easier one to fix than I originally thought ...

The issue is that there are tests that call `jwt.decode` directly and not inside `sanic_jwt`. The tests need to be fixed.

Easy PR for anyone that wants to jump in.

**Comment by ahopkins** [comment]
Thanks to @amor71, this can close.
