### ISSUE TITLE
Security issue when using an empty token with the authorization header

### ISSUE THREAD

**Issue by cipriantarta** [ahopkins/sanic-jwt#143]
If the authentication header is provided with no value for the actual token, the /verify endpoint for example returns a valid response:

`curl http://localhost:8000/auth/verify -H "Authorization: Bearer "`
results in:

`{"valid":true}`

**Comment by ahopkins** [comment]
Wow. :flushed: 

Nice find, and thanks for the quick PR. I am pulling it in and will prepare a new release to PyPI today.
