### ISSUE TITLE
Authentication instance not found exception when access /me uri 

### ISSUE THREAD

**Issue by greentornado** [ahopkins/sanic-jwt#147]
I'm planning to attach multiple blueprints (each with a sanic jwt) to a sanic app

I import my blueprint as
`import server.blueprints.auth.admins as bp_auth_admins`

And Init it
```
admin_jwt = Initialize(bp_auth_admins.bp, app=app, url_prefix='/jwt',
                       authenticate=bp_auth_admins.authenticate, 
                       store_refresh_token=bp_auth_admins.store_refresh_token,
                       retrieve_refresh_token=bp_auth_admins.retrieve_refresh_token,
                       retrieve_user=bp_auth_admins.retrieve_user,
                       responses_class=bp_auth_admins.JWTResponses,
                       configuration_class=bp_auth_admins.JWTConfiguration,
                       refresh_token_enabled=True,
                       )
```

I can login, verify token but when access /me, I got this exception, please help 

```
Authentication instance not found. Perhaps you used @protected without passing in a blueprint? Try @protected(blueprint) 

```

Sanic-jwt version 1.2.1

**Comment by ahopkins** [comment]
I am **so sorry** it took me 20 days to respond.

Initially, that did sound weird that `/jwt/verify` would work but `/jwt/me` would not.

But, it looks like you have uncovered a bug here: https://github.com/ahopkins/sanic-jwt/blob/dev/sanic_jwt/endpoints.py#L75

I will work on a fix for this later tonight and try to roll something out.

**Comment by greentornado** [comment]
oh glad I can help..
Thank u

**Comment by ahopkins** [comment]
See [98edc54](https://github.com/ahopkins/sanic-jwt/commit/98edc54cb12a92e3be9989944535eaa0599318ad) for the fix. Will push up to pypi soon.

**Comment by greentornado** [comment]
Great.!
