### ISSUE TITLE
RefreshTokenNotImplemented

### ISSUE THREAD

**Issue by priyolahiri** [ahopkins/sanic-jwt#148]
I get a refresh token not implemented exception even though I have followed the instructions in the documentation.

Here is my init:

```
Initialize(
    app,
    authenticate=auth.authenticate,
    refresh_token_enabled=True,
    store_refresh_token=auth.store_refresh_token,
    retrieve_refresh_token=auth.get_refresh_token
)
```

Also here's the auth module where the functions are

```
def store_refresh_token(user_id, refresh_token, *args, **kwargs):
    r_key = f'refresh_token_{user_id}'
    set_redis_key(r_key, refresh_token)

def get_refresh_token(request, user_id, *args, **kwargs):
    r_key = f'refresh_token_{user_id}'
    return get_redis_key(r_key)
```

Also my authenticate function which return a str id from Mongo for the user

```
def authenticate(request, *args, **kwargs):
    """
    Authentication stub for Sanic JWT implementation
    """
    email = request.json.get("email", None)
    password = request.json.get("password", None)
    lf_domain = request['lfdomain']
    if not email or not password:
        raise exceptions.AuthenticationFailed("Missing username or password.")
    user = try_auth(email, password, lf_domain)
    if not user:
        raise exceptions.AuthenticationFailed("Authentication details incorrect.")
    return {'user_id': str(user['_id'])}
```

Browsing redis shows me that the keys and values exist. Issuing an access token works fine. 

Any pointers?

**Comment by norbertparti** [comment]
Same issue here. Refresh token generated and it is also in Redis.

**Comment by norbertparti** [comment]
After downgrading the lib I found some different error message related to retrieve_user method should be implemented.
So implement it like [this](https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html?highlight=retrieve_user#retrieve-user)

Then:
```python
Initialize(
    app,
    refresh_token_enabled=True,
    retrieve_user=retrieve_user,
    store_refresh_token=store_refresh_token,
    retrieve_refresh_token=retrieve_refresh_token,
    authenticate=authenticate,
)
```

It is working for me now.

**Comment by norbertparti** [comment]
It would be nice a more descriptive exception.

**Comment by ahopkins** [comment]
@priyolahiri and @norbertparti First my apologies for not responding sooner.

I will be putting together a couple changes later tonight and will add that. Nice catch.

**Comment by ahopkins** [comment]
New error message:

```Refresh tokens have not been enabled properly. Perhaps you forgot to initialize with a retrieve_user handler?```

**Comment by amor71** [comment]
@ahopkins I run into the same issue, may I suggest a default implementation that won't raise an exception of missing implementation? basically just returning the user_id as in one of the examples... ? Maybe I'm missing something here.

**Comment by ahopkins** [comment]
@amor71 Something like this?

https://github.com/ahopkins/sanic-jwt/blob/master/example/main.py

**Comment by amor71** [comment]
yes, along these lines

**Comment by Antisunny** [comment]
## sanic_jwt v1.3.2

To make `/auth/refresh` work,  functions below should be reimplemented.

```python
class AuthModel(Authentication):
    async def store_refresh_token(self, user_id, refresh_token, *args, **kwargs)
    async def retrieve_refresh_token(self, user_id, *args, **kwargs)
    async def generate_refresh_token(self, request, user):
    async def retrieve_user(self, request, payload, *args, **kwargs)
```
Note, `retrieve_user` is **required**.
