### ISSUE TITLE
custom authentication control

### ISSUE THREAD

**Issue by its-a-feature** [ahopkins/sanic-jwt#158]
I'm trying to add in a feature for people to create `permanent api tokens` for use with my application in conjunction with the normal access/refresh tokens that users experience either via a browser or via CLI. The use case is they want an API token that can be used to easily script out access with my application. When a user creates one of these new API tokens for themselves, I save that token and all of the user's information into a database so I can look it up later. This should theoretically allow me to look up a user's information based on this new token (and allow it to be revoked by simply removing it from the database). However, I'm having some trouble getting this to work. 

I added in the following to successfully return either the normal header token or my new api token:
```python
class MyConfig(Configuration):
    def get_authorization_header(self, request):
        if "apitoken" in request.headers:
            return "apitoken"
        return "authorization"

    def get_authorization_header_prefix(self, request):
        if "apitoken" in request.headers:
            return ""
        return "Bearer"
```
The above seems to be working, but I can't seem to add in my own custom verification/authentication check anywhere. For an individual endpoint that I create in the my_views section, I can successfully do the following to get all of the user's api tokens (given normal access token or new api token):
```python
async def get(self, request, *args, **kwargs):
        try:
            payload = self.instance.auth.extract_payload(request, verify=True)
            try:
                user = await utils.call(
                    self.instance.auth.retrieve_user, request, payload=payload
                )
                user_id = await self.instance.auth._get_user_id(user)
            except Exception as e:
                return json({"status": "error", "error": "failed to get user from token"})
        except Exception as e:
            print("can't parse token as JWT, gonna try database lookup")
            try:
                if 'apitoken' in request.headers:
                    try:
                        query = await db_model.apitokens_query()
                        db_apitoken = await db_objects.get(query, token=request.headers.get('apitoken'))
                        user_id = db_apitoken.operator.id
                    except Exception as e:
                        print("Failed to find api token in db")
                        return json({"status": "error", "error": "Failed to find api token in db"})
                else:
                    return json({"failed to find token to authenticate with"})
            except Exception as e:
                raise e
        query = await db_model.operator_query()
        operator = await db_objects.get(query, id=user_id)
        query = await db_model.apitokens_query()
        tokens = await db_objects.execute(query.where(db_model.APITokens.operator == operator))
        return json({"status": "success", "tokens": [t.to_json() for t in tokens]})
```
I can't get this to work for any arbitrary endpoint though. With debug True I get:
`{"reasons":["Not enough segments."],"exception":"Unauthorized"}`, with debug False I get `{"reasons":["Auth required."],"exception":"Unauthorized"}`.

I've tried extending the responses class, but it never seems to be called:
```python
class MyResponses(Responses):
    @staticmethod
    async def extend_retrieve_user(request, user=None, payload=None):
        print("called extend retrieve user")
        return await retrieve_user(request, payload)

    @staticmethod
    async def extend_verify(request, user=None, payload=None):
        print("called extend verify")
        return {"Verify": True}
```
and I've even tried extending authenticate:
```python
class MyAuthentication(Authentication):
    async def authenticate(self, request, *args, **kwargs):
        print("called authenticate")
        return {"user_id": 1}
```
But i still don't see my print statements showing up, so these aren't getting called. I have all of the following added to my `Initialize` function as well:
```python
authenticate=app.routes.authentication.authenticate,
           retrieve_user=app.routes.authentication.retrieve_user,
           cookie_set=True,
           cookie_strict=False,
           cookie_access_token_name='access_token',
           cookie_refresh_token_name='refresh_token',
           cookie_httponly=True,
           scopes_enabled=True,
           add_scopes_to_payload=app.routes.authentication.add_scopes_to_payload,
           scopes_name='scope',
           secret='apfell_secret jwt for signing here',
           url_prefix='/',
           class_views=my_views,
           path_to_authenticate='/auth',
           path_to_retrieve_user='/me',
           path_to_verify='/verify',
           path_to_refresh='/refresh',
           refresh_token_enabled=True,
           expiration_delta=14400,  # initial token expiration time
           store_refresh_token=app.routes.authentication.store_refresh_token,
           retrieve_refresh_token=app.routes.authentication.retrieve_refresh_token,
           configuration_class=MyConfig,
           responses_class=MyResponses,
           authentication_class=MyAuthentication,
           debug=True)
```
What am I missing to enable this kind of override check?

**Comment by its-a-feature** [comment]
I also keep getting: `get_authorization_header() missing 1 required positional argument: 'request'` for my MyConfiguration class

**Comment by ahopkins** [comment]
@its-a-feature This sounds like an interesting challenge. 

I am going to try and come at it from a slightly different approach. I think my solution provides what you are looking for, but let me know if not.

## Starting point 

First, I want to start by exploring [example/custom_authentication_cls.py](https://github.com/ahopkins/sanic-jwt/blob/717f21ea3bec9338d1d3b74ef57af486d3fcaee5/example/custom_authentication_cls.py).

Try running that in one terminal session. Then in another, let's try hitting it. You should see something like this:

```
$ curl -H 'Content-Type: application/json' \
    -d '{"username": "foo", "password": "bar"}' \
    -X POST localhost:8000/auth

{"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE1NTY0NDI0ODZ9.8xCv9F_LsNdyTjhxV0P0Jw8H56_D_gkriPJjdRnKE6M","refresh_token":"38a8698cfa102948b98dc403a0b7e93d41f390ccb9219707"}

$ curl -H "Authorization: Bearer ${JWT}" \
    localhost:8000/cache

{"refresh_token_1":"38a8698cfa102948b98dc403a0b7e93d41f390ccb9219707"}
```

This is the starting point that I used for [a more complete example](https://github.com/ahopkins/sanic-jwt/blob/717f21ea3bec9338d1d3b74ef57af486d3fcaee5/example/custom_authentication_cls_complex.py).

## Working example

In the working example, the goals were:

1. Allow normal functioning of `sanic-jwt`, everything should work as expected
1. In addition, allow for a `permakey` to be stored in the database that:
    1. Does not expire
    1. Must be verified in place of a JWT
    1. Presented to the user upon logging in
    1. Can be used in place of an access token by changing the request header

In this second example, the operative parts are achieved by [overriding components](https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html#component-overrides).

```python
from sanic_jwt import Authentication, Configuration, Initialize)

class MyAuthentication(Authentication):
    def _verify(...): ...
    async def authenticate(...): ...

class MyConfiguration(Configuration):
    def get_verify_exp(...): ...

Initialize(
    app,
    authentication_class=MyAuthentication,
    configuration_class=MyConfiguration,
    ...)
```

### Easy Stuff

First, to explain some of the non-critical things that are going on here.

#### Custom response

```python
class MyResponses(Responses):
    @staticmethod
    def extend_authenticate(
        request, user=None, access_token=None, refresh_token=None
    ):
        return {"permakey": user.permakey}

Initialize(..., responses_class=MyResponses,)
```

I wanted the return of the `/auth` endpoint to provide me with an `access_token` (that would expire), and the user's `permakey`. This is accomplished by [overriding the `response_class`](https://sanic-jwt.readthedocs.io/en/latest/pages/endpoints.html#modify-responses) with the appropriate extender.

#### Custom claims

```python
class RandomClaim(Claim):
    key = "rand"

    def setup(self, *args, **kwargs):
        return random.random()

    def verify(self, *args, **kwargs):
        return True
```

When the `/auth` endpoint returns, it should have:

```
{
    "access_token": "...",
    "permakey": "...",
}
```

But, I want to ensure that they had unique payloads. So, I simply am adding a simple custom claim. This is entirely unnecessary, but is just here for showing how something like this could be done.

#### Expiration

```python
Initialize(
    ....
    expiration_delta=15,
    leeway=0,
)
```

When we are done, we want to verify that the `access_token` will expire as expected, but that the `permakey` will not expire.

Therefore, I set the `expiration_delta` to **15 seconds**, and made sure that there is **no leeway** to accept an expired token.

#### Authenticate

```python
    async def authenticate(self, request, *args, **kwargs):
        username = request.json.get("username", None)
        password = request.json.get("password", None)

        if not username or not password:
            raise exceptions.AuthenticationFailed(
                "Missing username or password."
            )

        # Here, you would want to try to verify the username and password.
        # In this example, we are simply creating a new user if it does not
        # exist, and then authenticating the new user.
        user = username_table.get(username)
        if not user:
            user = User(len(USERS) + 1, username)
            USERS.append(user)
            username_table.update({user.username: user})
            userid_table.update({user.user_id: user})

            user.permakey = await self.generate_access_token(user)

        user.last_login = datetime.utcnow().strftime("%c")

        return user
````

The [`authenticate` method](https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html#authenticate-required) is nothing special. Basically we are going to accept any request that passes a `username` and `password`. If the `username` is not in our DB, then add it. Clearly this is not something you would use in your app.

#### Retrieve user

```python
    async def retrieve_user(self, request, payload, *args, **kwargs):
        if payload:
            user_id = payload.get("user_id", None)
            return userid_table.get(user_id)

        else:
            return None
```

This was added so that the `/auth/me` endpoint would be available to us.

---

With that all out of the way...

### Making it all work

#### Should verify expiration?

```python
class MyConfig(Configuration):
    def get_verify_exp(self, request):
        return not "permakey" in request.headers
```

Ideally, when the claims are being built, there would not even be an `exp` claim in the `permakey` token, but only for ther `access_token`. If I were building this as a production worthy application, I would do that. But, it is a little more complex than the scope of what I am trying to achieve here.

Regardless, when there is `Authorization: Beaded <JWT>`, then we want to make sure to verify that the token is not expired. When the header is `Permakey: <JWT>`, then we want to skip that.

#### Token verification

In the [example](https://github.com/ahopkins/sanic-jwt/blob/717f21ea3bec9338d1d3b74ef57af486d3fcaee5/example/custom_authentication_cls_complex.py#L65), I make the point that **typically** `Authentication._verify` is not a method you want to be messing around with. Changing it **could lead to a SECURITY VULNERABILITY**.

This basically does the following:

- If processing for a regular `access_token`, do the normal thing
- If processing for a `permakey`:
    - Decode the token and pull back the proper user from the database
    - Make sure the token and the user's `permakey` (from the DB) match

## Seeing it in action

Let's run the code and see what happens...

```
$ curl -H 'Content-Type: application/json' \
    -d '{"username": "foo", "password": "bar"}' \
    -X POST localhost:8000/auth

{
  "access_token": ...,
  "permakey": ...
}

```

So far, so good. Now, let's check if it works. Be quick here because our `access_token` is only alive for **15 seconds**.

```
$ curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \  
    localhost:8000/protected                     

{
    "protected": true
}
```

And ... if we wait a few more seconds

```
$ curl -H "Authorization: Bearer ${ACCESS_TOKEN}" \  
    localhost:8000/protected                     

{
  "reasons": [
    "Signature has expired."
  ],
  "exception": "Unauthorized"
}
```

Now, let's see what happens if we try with the `permakey`:

```
$ curl -H "Permakey: ${PERMAKEY}" \  
    localhost:8000/protected                     

{
    "protected": true
}

It still works even though more than **15 seconds** have past.

Let's see what users are in the DB:

```
$ curl -H "Permakey: ${PERMAKEY}" \
    localhost:8000/cache

{
  "1": {
    "last_login": "Sun Apr 28 12:19:18 2019",
    "permakey": ...,
    "user_id": 1,
    "username": "foo"
  }
}
```

And, how about see who is currently logged in:

```
$ curl -H "Permakey: ${PERMAKEY}" \
    localhost:8000/auth/me 

{
  "me": {
    "user_id": 1,
    "username": "foo",
    "last_login": "Sun Apr 28 12:19:18 2019"
  }
}
```

But ... what if I put in the wrong key?

```
$ curl -H "Permakey: qqqq" \       
    localhost:8000/auth/me

{
  "reasons": [
    "Auth required."
  ],
  "exception": "Unauthorized"
}
```

How about a `permakey` that evaluates to the proper payload and retrieves my user ... but is not the `permakey` in my database?

```
$ curl -H "Permakey: ${DELETED_PERMAKEY}" \         
    localhost:8000/protected

{
  "reasons": [
    "Permakey mismatch"
  ],
  "exception": "Unauthorized"
}
```

---

Sorry for the lengthy response here. It turned out to be a nice example use case to show off how some things might be accomplished in `sanic-jwt`. I hope that after all of this that my solution helps you and is not completely off base. Please let me know.

**Comment by its-a-feature** [comment]
Wow, this is amazingly in-depth! I really appreciate this :) I'm working through it now to work that into my project, but I am running into one issue already - the `_verify` method seems to be synchronous only? If I try to change it to an `async def`, I get an error that it's not being awaited. Is there a reason that some of these methods are sync and some are async?

The reason that's an issue for me is that the lookups to my database to get information about the token/user specified in the permatoken are async :/

**Comment by ahopkins** [comment]
🤔 Good point. 

Typically, the decision to make a method async was determined by whether it was something that might need to make async calls inside it. I never intended *_verify* to be used this way.

We have two potential options. (1) Hijack some more internals and allow for it to be awaitable, or (2) retrieve user perhaps a bit further upstream and attach it to something like the request object. I'll try and see if I can get a working example for you.

**Comment by ahopkins** [comment]
I am using the [`@inject_user`](https://sanic-jwt.readthedocs.io/en/latest/pages/protected.html#inject-user-decorator) decorator to get the user and have it available in `Authentication._verify`. This also will make the `user` available in all of the handlers.

Doing this will make a call to your [`retrieve_user`](https://sanic-jwt.readthedocs.io/en/latest/pages/initialization.html#retrieve-user) handler. This method **CAN** be either sync (`def my_handler`) or async (`async def myhandler`). 

The parts that change are as follows:

```python
# Helpful to have catch this exception in case we need it since we are skipping the section that would normally do this.
from jwt.exceptions import DecodeError

...

    # This should now have `request_kwargs['user']` available to it. Let's use that instead of having to grab the user here.
    def _verify(
        self,
        request,
        return_payload=False,
        verify=True,
        raise_missing=False,
        request_args=None,
        request_kwargs=None,
        *args,
        **kwargs
    ):
        ...
        if "permakey" in request.headers:
            # Extract the permakey from the headers
            permakey = request.headers.get("permakey")

            try:
                payload = self._decode(permakey, verify=verify)
            except DecodeError:
                if return_payload:
                    return {}
                return False, 400, "Invalid token format"

            # Sometimes, the application will call _verify(...return_payload=True)
            # So, let's make sure to handle this scenario.
            if return_payload:
                return payload

            request_kwargs = request_kwargs or {}
            user = request_kwargs.get("user")
            # If wer cannot find a user, then this method should return
            # is_valid == False
            # reason == some text for why
            # status == some status code, probably a 401
            if not user:
                is_valid = False
                reason = "No user found"
                status = 401
            else:
                # After finding a user, make sure the permakey matches,
                # or else return a bad status or some other error.
                # In production, both this scenario, and the above "No user found"
                # scenario should return an identical message and status code.
                # This is to prevent your application accidentally
                # leaking information about the existence or non-existence of users.
                is_valid = user.permakey == permakey
                reason = None if is_valid else "Permakey mismatch"
                status = 200 if is_valid else 401

            return is_valid, status, reason
        ...

    # We now need to wrap the endpoint also with `inject_user`, and make sure we allow for it to be passed as a `kwarg` to the handler.
    @app.route("/protected")
    @sanicjwt.inject_user()
    @sanicjwt.protected()
    async def protected_request(request, user):
        return json({"protected": True})
```

---

Since you are skipping part of the normal `_verify` process that catches some problems with tokens, in addition to `DecodeError`, here are some others that you might want to catch as well.
```python
jwt.exceptions.InvalidIssuerError
jwt.exceptions.ImmatureSignatureError
jwt.exceptions.InvalidIssuedAtError
jwt.exceptions.InvalidAudienceError
InvalidVerificationError
InvalidCustomClaimError
```

I created [a gist](https://gist.github.com/ahopkins/912e1cf48fa322355f78522328a541b3) with the full modified code.

**Comment by its-a-feature** [comment]
Ah ok yup, that should fix that issue! And I do like just being able to access the user keyword within the _verify. The next thing I'm trying to figure out is how to generate the permakey outside of these subclassed functions. Essentially, I'm wanting to do some management of these new api tokens (since they are so powerful), so I want RESTful endpoints that can generate them as needed. This allows me to 'deactivate' or completely remove them at any time and still create new ones with different purposes. The RESTful endpoint will already have the @protected and @inject_user decorators, so I would think it's possible somewhere

**Comment by ahopkins** [comment]
Glad to hear that this is helpful.

There's no secret to creating JWTs. [This is the underlying repo used to create them](https://github.com/jpadilla/pyjwt). You could use it directly if you wanted. But, there are some helpful bits that `sanic-jwt` will add.

For example: the `app.auth` instance of the `Authentication` class has `auth.generate_access_token(user)`. You also can modify the payload by [extending it](https://sanic-jwt.readthedocs.io/en/latest/pages/configuration.html#user-id) or [adding a custom claim](https://sanic-jwt.readthedocs.io/en/latest/pages/payload.html#custom-claims).

Here is an example that pulls it all together.

```python
from sanic import Sanic
from sanic.response import text
from sanic_jwt import Claim, Initialize


class FooClaim(Claim):
    key = 'foo'

    def setup(self, payload, user):
        return 'bar'

    def verify(self, value):
        return value == 'bar'


async def baz_payload_extender(payload, *args, **kwargs):
    payload.update({
        'baz': 'qux'
    })

    return payload


user = {"user_id": 1}
app = Sanic(__name__)
Initialize(
    app,
    authenticate=lambda _: user,
    custom_claims=[FooClaim],
    extend_payload=baz_payload_extender
)


@app.get("/")
async def new_token(request):
    permakey = await request.app.auth.generate_access_token(user)
    return text(f"new permakey: {permakey}")


if __name__ == '__main__':
    app.run(debug=True)

```

If you authenticate a new user, its token's payload would have something like this:

```json
{
  "user_id": 1,
  "exp": 1557779554,
  "foo": "bar",
  "baz": "qux"
}
```

**Comment by its-a-feature** [comment]
Getting closer! I wanted to add in the ability to differentiate how I'm authenticating to the system - for example, maybe authenticating with this permakey only gives you limited access. My thought process was to add scopes so that I could mark certain routes as not only protected, but only accessible if you're going through the browser, or with the permakey.

However, when I add a scope to a route, I get an error :/ 
```
[2019-05-13 18:55:49 -0700] [16240] [ERROR] Exception occurred while handling uri: 'http://192.168.205.151/api/v1.2/apitokens'
Traceback (most recent call last):
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
    response = await response
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/decorators.py", line 222, in decorated_function
    return await response
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/decorators.py", line 157, in decorated_function
    user_scopes = instance.auth.extract_scopes(request)
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/authentication.py", line 426, in extract_scopes
    payload = self.extract_payload(request)
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/authentication.py", line 418, in extract_payload
    request, return_payload=True, verify=verify, *args, **kwargs
  File "/home/its-a-feature/Desktop/Apfell/apfell-docker/app/routes/authentication.py", line 76, in _verify
    **kwargs
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/authentication.py", line 348, in _verify
    payload = self._decode(token, verify=verify)
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/authentication.py", line 171, in _decode
    options={"verify_exp": self.config.verify_exp()},
  File "/home/its-a-feature/.local/lib/python3.6/site-packages/sanic_jwt/configuration.py", line 132, in __call__
    val = self._get_from_config.__call__(*args)
TypeError: get_verify_exp() missing 1 required positional argument: 'request'
[2019-05-13 18:55:49 -0700] - (sanic.access)[INFO][192.168.205.151:59060]: GET http://192.168.205.151/api/v1.2/apitokens  500 144
```
And all I did was add `@scoped('auth')` instead of `@protected()` to a route. Within my code, it's throwing the error at :
```
return super()._verify(
                request=request,
                return_payload=return_payload,
                verify=verify,
                raise_missing=raise_missing,
                request_args=request_args,
                request_kwargs=request_kwargs,
                *args,
                **kwargs
            )
``` 
in the `_verify` override where I just call the super method if the `permakey` isn't in the request headers.
I get the same error if I supply my new permakey too:
```
 if "apitoken" in request.headers:
            # Extract the apitoken from the headers
            apitoken = request.headers.get("apitoken")

            try:
                payload = self._decode(apitoken, verify=verify)
            except Exception as e:
                print(e)
                print("Failed to decode apitoken")
                if return_payload:
                    return {}
                return False, 401, "Auth Error"
```
it fails the `self._decode` with the same error about missing the required argument. Thoughts? If I change it back to `@protected()` then everything works just fine.

**Comment by ahopkins** [comment]
Well, we are doing some things here slightly out of the intended use case. I am going to mull this over in my head and see if it is something I want to adapt the library to handle.

Regardless, there is a fairly simple solution for you:

```python
from contextlib import contextmanager
from sanic_jwt.cache import to_cache, clear_cache

@contextmanager
def cache_request(request):
    to_cache("_request", request)
    yield
    clear_cache()
```

Then, we will wrap your call to `self._decode` with this contextmanager:

```python
try:
    with cache_request(request):
        payload = self._decode(apitoken, verify=verify)
except DecodeError:
    if return_payload:
        return {}
    return False, 401, "Auth Error"
```

**Comment by ahopkins** [comment]
I am closing this now as there is no "issue" here. Please feel free to continue the conversation and let me know if you run into anything else.
