### ISSUE TITLE
add_scopes_to_payload is never called

### ISSUE THREAD

**Issue by bastiendonjon** [ahopkins/sanic-jwt#160]
Hello,

I dont undertand "add_scopes_to_payload" handler is never called.

```python
app = Sanic(__name__)

@app.route('/test')
@scoped('admin')
async def open_route(request):
    return json({'protected test': False})

def my_scope_extender(user, *args, **kwargs):
    return 'admin'

Initialize(
    app,
    authenticate=authenticate,
    retrieve_user=retrieve_user,
    add_scopes_to_payload=my_scope_extender,
    user_id='id',
    secret="secret"
)
```
Where i test route "/test", i have this response :
```json
{
	"exception": "Unauthorized",
	"reasons": [
		"Invalid scope."
	]
}
```

Thanks

**Comment by bastiendonjon** [comment]
Ok my token was not updated with scopes value.

I have refresh my token.

**Comment by ahopkins** [comment]
👍

Just as a "gotcha" in case anyone lands here, if your add_scopes_to_payload method is in a subclass of Authentication instead of passed thru Initialize, you need to manually set the config option scopes_enabled=True.

Not an issue the way you have it, but more of just an FYI.
