### ISSUE TITLE
custom claims post refresh 

### ISSUE THREAD

**Issue by amor71** [ahopkins/sanic-jwt#168]
Is it possible that the access_token returned during refresh does not include custom claims? Is it by design, or maybe I'm doing something wrong?

Here is the code sample from my unit test:

    print(access_token)
    headers = {"Authorization": f"Bearer {access_token}"}
    resp = await test_cli.post(
        "/auth/refresh", headers=headers, data=json.dumps(data)
    )
    resp_json = await resp.json()
    print(resp_json)

Here is the result:
**eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5MiwiZXhwIjoxNTU5Mjg5NzE4LCJpYXQiOjE1NTkyODc5MTgsImVtYWlsIjoiYW1pY2hheS5vcmVuKzE0MzlAZ21haWwuY29tIiwibmFtZSI6IkFtaWNoYXkgT3JlbiJ9.ZHHl12bennfwRfHRNM23l25SbXT6tQFOUMoHdBrDhFg**
[2019-05-31 10:31:59 +0300] - (sanic.access)[INFO][127.0.0.1:59761]: POST http://127.0.0.1:59760/auth/refresh  200 198
{'access_token': '**eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5MiwiZXhwIjoxNTU5Mjg5NzE5LCJpYXQiOjE1NTkyODc5MTksImVtYWlsIjpudWxsLCJuYW1lIjpudWxsfQ.x64sTrc76hTCvoju-mHR01D5KQCJ-XrDRmOLPBHXllU**'}

**Comment by ahopkins** [comment]
@amor71 Were you able to resolve this?

**Comment by amor71** [comment]
Yes, thank you, was good learning.
