### ISSUE TITLE
Question to add blacklist verification

### ISSUE THREAD

**Issue by geohuz** [ahopkins/sanic-jwt#169]
I have dig into documentation and git issues, but I was unable to make it clear on how to get the job done, my goal is using the user_id or jit field to add a blacklist of token into cache, but I'm stuck on how to add verification on every request to make sure we don't allow blacklisted token through. I saw extra_verifications, modify Response add staticmethod like extend_verify, but I'm still unsure what is the official way to cope this scenario.

**Comment by ahopkins** [comment]
Sorry for the slow response. I had a very busy week at work, and was also at PyCon Israel.

Are you specifically talking about blacklisting access tokens, or any token that contains a payload with a blacklisted `user_id`? I think the best way would be in `extra_verifications`. If you let me know your thought I will try and put together a quick sample.

**Comment by ahopkins** [comment]
Take a look [at the `extra_verifications.py` example](https://github.com/ahopkins/sanic-jwt/blob/master/example/extra_verifications.py). It basically does exactly what you want, except in the opposite. 

---

Here is what the linked to above example would look like.

```
$ curl -X POST -d '{"username":"user1","password":"abcxyz"}' localhost:8888/auth                                                                       127 ↵
{"access_token":"<JWT1>"}

$ curl -X POST -d '{"username":"user2","password":"abcxyz"}' localhost:8888/auth
{"access_token":"<JWT2>"}

$ JWT=<JWT1>
$ curl -H "Authorization: Bearer ${JWT}" localhost:8888/protected                                                              
{"reasons":["Verifications were not met."],"exception":"Unauthorized"}

$ JWT=<JWT2>
$ curl -H "Authorization: Bearer ${JWT}" localhost:8888/protected                                                              
{"protected":true}
```

---

The extra verification method is setup to make sure that the payload has `user_id==2`. Just change that to:

```python
def not_in_blacklist(payload):
    return payload.get("user_id") not in MY_BLACKLIST


extra_verifications = [not_in_blacklist]

app = Sanic()
Initialize(
    app, authenticate=authenticate, extra_verifications=extra_verifications
)

```

**Comment by ahopkins** [comment]
Marking this closed. Please let me know if you have any more discussion.
