### ISSUE TITLE
Blueprint Initialize fails on Blueprint instance check

### ISSUE THREAD

**Issue by razvanctatu** [ahopkins/sanic-jwt#170]
Running the example in the documentation
```
from sanic_jwt import Initialize
from sanic import Sanic, Blueprint

app = Sanic()
bp = Blueprint('my_blueprint')
Initialize(bp, authenticate=lambda: True)
app.blueprint(bp)
```

fails with `sanic_jwt.exceptions.InitializationFailure: Sanic JWT was not initialized properly. It must be instantiated on a sanic.Sanic or sanic.Blueprint instance.`

Printing the type of `bp` shows its type to be `class 'sanic.blueprints.Blueprint'`

**Comment by kaushall** [comment]
I'm also getting the same issue

**Comment by kaushall** [comment]
@razvanctatu You can bypass it by adding a kwarg app=app

Initialize(bp, authenticate=lambda: True, app=app)

**Comment by ahopkins** [comment]
Thanks @kaushall. Looks like a documentation bug.

**Comment by SirTelemak** [comment]
We can also make some dynamic checking if there app bypassed with blueprint so it won't raise confusing exception

**Comment by ahopkins** [comment]
@SirTelemak 

What exactly do you mean?

We need to be able to get to the instance of `Sanic()`. But, since the `Blueprint` can be initialized before there is an app, there isn't necessarily a way to do it without explicitly passing the `app=app` argument.

**Comment by SirTelemak** [comment]
I mean we can add some checks so: 
```
from sanic_jwt import Initialize
from sanic import Sanic, Blueprint

app = Sanic()
bp = Blueprint('my_blueprint')
Initialize(bp, authenticate=lambda: True)
app.blueprint(bp)
```
Will raise something more specific like: `sanic_jwt.exceptions.InitializationFailure: Sanic JWT was not initialized properly. sanic.Sanic wasn't found in sanic.Blueprint instance, pass app explicitly or add register blueprint in app`
Since `It must be instantiated on a sanic.Sanic or sanic.Blueprint instance.` could be little confusing since there is  sanic.Blueprint instance

**Comment by ahopkins** [comment]
Ahh... got it. Thanks.

**Comment by SirTelemak** [comment]
If it's fine I'll make PR tomorrow

**Comment by ahopkins** [comment]
Awesome. Something like this...

```python
    @staticmethod
    def __get_app(instance, app=None):
        if isinstance(instance, Sanic):
            return instance

        elif isinstance(instance, Blueprint):
            if app is not None:
                return app
            message = "Sanic JWT was not initialized properly. When "
            "instantiating on a sanic.Blueprint you must pass your app "
            "instance: Initialize(bp, app=app, ...)"
            raise exceptions.InitializationFailure(message=message)

        raise exceptions.InitializationFailure
```

**Comment by ahopkins** [comment]
Closing. See #179
