### ISSUE TITLE
How to redirect to login page when protected route is hitted?

### ISSUE THREAD

**Issue by zwjat** [ahopkins/sanic-jwt#176]
When a route is protected, request to it will result Unauthorized exception. But I want to redirect login page to fill username and password to authenticate. I am sorry I don't know where and how I can put code to inplement it. Could anyone help me ? Thank a lot.

**Comment by ahopkins** [comment]
For the sake of anyone else that stumbles upon this: [see docs](https://sanic-jwt.readthedocs.io/en/latest/pages/configuration.html#login-redirect-url)
