### ISSUE TITLE
How to redirect to previous protected route when auth is passed?

### ISSUE THREAD

**Issue by zwjat** [ahopkins/sanic-jwt#177]
How to redirect to previous protected route when auth is passed instead of return of access_token ?

**Comment by ahopkins** [comment]
What you could do is make a [custom endpoint](https://sanic-jwt.readthedocs.io/en/latest/pages/endpoints.html#custom-endpoints) and then within that endpoint return a [redirect response](https://sanic.readthedocs.io/en/latest/sanic/response.html#redirect). Or, another option would be to subclass the `AuthenticationEndpoint` kind of like this...

```python
from sanic_jwt.endpoints import AuthenticationEndpoint
from sanic import response

class RedirectAuthentication(AuthenticationEndpoint):
    async def do_response(self, *args, **kwargs):
        return response.redirect('/go/here')
```

**Comment by zwjat** [comment]
In order to rediredt previous protected route, maybe sanic-jwt would have somewhat method to remember previous protected route.
`
from sanic_jwt.endpoints import AuthenticationEndpoint
from sanic import response

class RedirectAuthentication(AuthenticationEndpoint):
    async def do_response(self, *args, **kwargs):
        return response.redirect('/go/here')`

As show abve, '/go/here' should be remembered so that we can redirect to when auth is passed.
Do you have any recommand way to implement this?

**Comment by zwjat** [comment]
What is the right way to add RedirectAuthentication to sanic to redirect to previous protected route?

This is my code:

from sanic_jwt.endpoints import AuthenticateEndpoint
from sanic import response

class RedirectAuthentication(AuthenticateEndpoint):
    async def do_response(self, *args, **kwargs):
        return response.redirect('/')

Initialize(app, authenticate=authenticate, 
  configuration_class=JwtCfg, class_views=(('/signint.html', RedirectAuthentication),))

Then  error occurs:

  405 — Method Not Allowed  
  Method POST not allowed for URL /signint.html

Thank you for your helping.
