### ISSUE TITLE
Initialization on a group of blueprints

### ISSUE THREAD

**Issue by nogaems** [ahopkins/sanic-jwt#181]
Is there a solid reason why there's no option of initializing on a group of blueprints? Say, I have a nested structure of blueprints, like it's done in [sanic documentation](https://sanic.readthedocs.io/en/latest/sanic./blueprints.html#blueprint-groups-and-nesting). When I try to initialize on a corresponding `api` blueprint I get an error:
```
sanic_jwt.exceptions.InitializationFailure: Sanic JWT was not initialized properly. It must be instantiated on a sanic.Sanic or sanic.Blueprint instance.
```
My intention was to get `/auth` entry-point under `/v1/api`, is there any way to achieve that?

**Comment by ahopkins** [comment]
It should work if you create a BP at the `api` root. I will send a snippet later.

As the project currently stands, it does not stand up a Blueprint on a Blueprint Group. It either attaches to an existing Blueprint or creates a new Blueprint for your app. 

https://github.com/ahopkins/sanic-jwt/blob/master/sanic_jwt/initialization.py#L331

**Comment by nogaems** [comment]
Thanks for the quick response!
I guess, all I got to do is to specify `url_prefix` as `/v1/api/auth` manually during initialization?

**Comment by nogaems** [comment]
I've just checked, it works fine. Thanks for help, this issue can be closed.

**Comment by ahopkins** [comment]
Thanks for the update. I'm going to open an issue for Blueprint Group support.
