### ISSUE TITLE
expiration_delta

### ISSUE THREAD

**Issue by qtest84** [ahopkins/sanic-jwt#185]
No matter what I set less than 3 mins at expiration_delta, it always takes at least 3 mins.

Any way to set the expiration to short? 

app = Sanic(name='AuthService')
initialize(app, 
           authenticate=authenticate, 
           user_id='user_id',
           add_scopes_to_payload=my_scope_extender,
           secret='mytest',
           expiration_delta=30,
            )

Thank you.

**Comment by qtest84** [comment]
I found the solution. It should cooperate with "leeway"


app = Sanic(name='AuthService')
initialize(app,
authenticate=authenticate,
user_id='user_id',
add_scopes_to_payload=my_scope_extender,
secret='mytest',
expiration_delta=30,
### **leeway=0**
)

**Comment by ahopkins** [comment]
Probably could use a clarification in the docs.
