### ISSUE TITLE
"Authentication instance not found" for /auth/refresh on blueprint

### ISSUE THREAD

**Issue by megaexception** [ahopkins/sanic-jwt#190]
I took example [on_blueprint.py](https://github.com/ahopkins/sanic-jwt/blob/master/example/on_blueprint.py) and added refresh tokens:
```
sanicjwt = Initialize(
    blueprint,
    app=app,
    authenticate=authenticate,
    store_refresh_token=store,
    retrieve_refresh_token=retrieve,
    retrieve_user=getuser,
    refresh_token_enabled=True,
)
```
And now I can authenticate, can verify access_token. But as soon as I request refresh, I get error:
`{"reasons":["Authentication instance not found. Perhaps you used @protected without passing in a blueprint? Try @protected(blueprint)"],"exception":"SanicJWTException"}`

If I remove blueprint and attach sanic_jwt to app - everything works like a magic.
sanic-jwt==1.4.0

**Comment by ahopkins** [comment]
Can you show code for how you are using `@protected`?

**Comment by megaexception** [comment]
To reproduce I have used on_bluepront.py from sanic_jwt examples.
But I have no problems with protected routes - token validation works fine.
Problem arises only if I try to call /test/auth/refresh

```python
from sanic import Sanic
from sanic.blueprints import Blueprint
from sanic.response import json
from sanic_jwt import Initialize
from sanic_jwt.decorators import protected

blueprint = Blueprint("Test")

@blueprint.get("/somewhere", strict_slashes=True)
@protected(blueprint)
def protected_hello_world(request):
    return json({"message": "hello world"})

@blueprint.get("/user/<id>", strict_slashes=True)
@protected(blueprint)
def protected_user(request, id):
    return json({"user": id})

async def authenticate(request, *args, **kwargs):
    return {"user_id": 1}

TOKENS = {
    'refresh_token_root': '4cd3d09d3335012bdc2fd119bc42db26ca19feb3147769a3'
}

async def store(user_id, refresh_token, *args, **kwargs):
    print(f"Store: {user_id}: {refresh_token}")
    key = f'refresh_token_{user_id}'
    TOKENS[key] = refresh_token

async def retrieve(request, user_id, *args, **kwargs):
    print(f"Retrieve: {user_id}")
    key = f'refresh_token_{user_id}'
    return TOKENS.get(key)

async def getuser(req, payload, *args, **kwargs):
    if payload:
        return {"user_id": payload.get('user_id', None)}

app = Sanic(__name__)

sanicjwt = Initialize(
    blueprint,
    app=app,
    authenticate=authenticate,
    store_refresh_token=store,
    retrieve_refresh_token=retrieve,
    retrieve_user=getuser,
    refresh_token_enabled=True,
)

app.blueprint(blueprint, url_prefix="/test")

if __name__ == "__main__":
    print(app.router.routes_all)
    app.run(host="127.0.0.1", debug=True)
```

**Comment by ahopkins** [comment]
Okay. Looks like you uncovered a bug.

For now, I would suggest this hack:

```python
app.auth = blueprint.auth
```

The problem is with [this mapping](https://github.com/ahopkins/sanic-jwt/blob/f9fc2d5e47750b57c14cf1c8d2cd006333ca4166/sanic_jwt/initialization.py#L32). I will try to get a patch out early next week.

**Comment by ahopkins** [comment]
[Version 1.4.1](https://pypi.org/project/sanic-jwt/1.4.1/) should resolve this.

**Comment by ahopkins** [comment]
[See new unit test](https://github.com/ahopkins/sanic-jwt/blob/master/tests/test_endpoints_init_on_bp_single.py#L133)

**Comment by megaexception** [comment]
Thank you, 1.4.1 fixed problem for me

**Comment by ahopkins** [comment]
Glad to hear it. thank for bringing this toy attention 🍻
