### ISSUE TITLE
How to extend the payload with a "dynamic" field

### ISSUE THREAD

**Issue by jamespo** [ahopkins/sanic-jwt#193]
I have a custom auth endpoint using app.auth.generate_access_token(user) to create a cookie.

I'd like to add to the payload some variables which have been generated in the the auth function.

It's not clear to me how I do this with extend_payload as that seems to be for static fields.

**Comment by ahopkins** [comment]
I guess I am not 100% sure I understand what you are asking. You can use `extend_payload` to add whatever fields you want. They do not need to be the same for every single authentication (if that is the point).

```python
class MyAuthentication(Authentication):
    async def extend_payload(self, payload, *args, **kwargs):
        dynamic_field = datetime.now().strftime('%Y-%m-%d')
        payload.update({
            "app_name": self.app.name,
            dynamic_field: "foobar",
        })
        return payload
```

Maybe you can share a snippet of what you are doing in that endpoint and I could help?

Also, to make sure you know, `sanic-jwt` [can provide cookie based tokens](https://sanic-jwt.readthedocs.io/en/latest/pages/protected.html#cookie-tokens) as well.

**Comment by jamespo** [comment]
I guess I didn't explain this very well.

I ended up doing:

```
async def add_sessid(payload, user):
    '''add the sessid to the payload'''
    payload.update({"sessid": user.sessid})
    return payload

@app.route("/authit", methods=['POST'])
async def auth_it(request):
    # ...stuff...
    access_token = await app.auth.generate_access_token(player, add_sessid)
```
I then "manually" generate my cookie & send it out, but use sanic-jwt's auto protection / checking of routes.

**Comment by ahopkins** [comment]
You don't need to go through all that.

```python

def extender(payload, user):
    payload.update({"sessid": user.sessid})
    return payload

Initialize(..., extend_payload=extender)
```
