### ISSUE TITLE
Retreive user information on a non protected route ? 

### ISSUE THREAD

**Issue by sylvainbeo** [ahopkins/sanic-jwt#202]
Hi,

I was wondering if there was a simply way to retreive information of an authentified user on a non protected route ? 

I have a public route (not protected), but i would like to do different things if a connected user access it. 

Without the protected decorator,

```python
request.app.auth.is_authenticated(request)
```
returns always **False**.

And so,

```python
request.app.auth.extract_payload(request)
```

always returns None

Any tips ?

Thanks you.

**Comment by ahopkins** [comment]
The `inject_user` decorator [should be able to handle that](https://sanic-jwt.readthedocs.io/en/latest/pages/protected.html#inject-user-decorator).

```python
@app.get("/")
@inject_user()
async def public_route(request, user):
    print(user)
    return response.empty()
```

**Comment by ahopkins** [comment]
Also... You should be able to do this to get the payload:

```python
await request.app.auth.extract_payload(request, verify=False)
```

**Comment by sylvainbeo** [comment]
@ahopkins Thanks for the infos.

I've tried, and indeed the **request.app.auth.is_authenticated(request)** return the good state... but only when i call the route directly in a browser. When the url is called from JS, curiously it doesn't work (always return False)...

When i'll find what's going on, i let you know here.

**Comment by sylvainbeo** [comment]
@ahopkins Ok i got it.

It's working exactly as you described.

The problem i had was that i wasn't sending cookies information from the JS for that specific route. So...it couldn't properly work.
All is good now.

Thank you.

I close the issue.
