### ISSUE TITLE
The recent release of pyjwt (2.0.0) is not compatible with sanic-jwt: encode returned type is 'str'

### ISSUE THREAD

**Issue by garaud** [ahopkins/sanic-jwt#207]
Hi there,

I  know that Sanic-jwt depends on [pyjwt](https://github.com/jpadilla/pyjwt/). There is not specified version of this dependency from the `setup.py`.

The library pyjwt has been released (2.0.0) and I got this error:

```py
  File "venv/lib/python3.6/site-packages/sanic_jwt/authentication.py", line 477, in generate_access_token
    return jwt.encode(payload, secret, algorithm=algorithm).decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
```

Actually, the `jwt.encode` function returns a `str`, see also https://github.com/jpadilla/pyjwt/pull/521

I'll try to propose a fix soon.

Best,
Damien

**Comment by ahopkins** [comment]
Thanks. There's a PR for this already.

https://github.com/ahopkins/sanic-jwt/pull/206

I plan to make the changes to Travis to get the build running again and then merge and release this later today.

**Comment by garaud** [comment]
OK thanks!!

Sorry for my useless issue... :slightly_smiling_face: I didn't think to take a look to the current PR.

**Comment by py-paulo** [comment]
in line 498 file `authentication.py`
```
        try:
            jwt_encode = jwt.encode(payload, secret, algorithm=algorithm).decode("utf-8")
        except AttributeError:
            jwt_encode = jwt.encode(payload, secret, algorithm=algorithm)

        return jwt_encode
``´

**Comment by rahulraina7** [comment]
Fixed in https://github.com/ahopkins/sanic-jwt/pull/206

**Comment by garaud** [comment]
Thanks!
