### ISSUE TITLE
How to use the JWT token via auth headers and refresh_token via cookies

### ISSUE THREAD

**Issue by schneider8357** [ahopkins/sanic-jwt#210]
I do not have much experience with web apps security, but according to [this article](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#refresh_token_persistance), to protect my app from CSRF, I can store the JWT token in-memory and the refresh_token on a cookie. I then thought of storing only the `access_token_signature` in-memory, since it is required for the authentication.

So, in order to implement that, it would be necessary to customize the `/auth` endpoint to send the `access_token_signature` on the response data, and both the `refresh_token` and the `token-header-payload` on cookies. I want to know, first of all, your thoughts on this. And, secondly, if there is a way to make this happen.

[If I can monkey-patch the `/auth` endpoint](https://github.com/ahopkins/sanic-jwt/issues/204#issuecomment-808819144), it should be possible to do this separation. However, I'm not sure if this is the best way to accomplish this.

Thanks in advance.

**Comment by schneider8357** [comment]
Also, [this RFC draft](https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-00#section-8) states:

> Authorization servers SHOULD NOT issue refresh tokens to browser-
>   based applications.
>
>   If an authorization server does choose to issue refresh tokens to
>   browser-based applications, then it MUST issue a new refresh token
>   with every access token refresh response.  Doing this mitigates the
>   risk of a leaked refresh token, as a leaked refresh token can be
>   detected if both the attacker and the legitimate client attempt to
>   use the same refresh token.

**Comment by ahopkins** [comment]
Both of these are possible to do using the custom response feature.

**Comment by schneider8357** [comment]
Yeah, the reason why I closed this is that I fiddled with it and eventually got the result I wanted.
If you have any insights, though, about what's the most secure way of doing that, I'd very much appreciate it.
Thanks! =)
