### ISSUE TITLE
instance.auth will not support in the future

### ISSUE THREAD

**Issue by yj0520** [ahopkins/sanic-jwt#211]
Setting variables on Blueprint instances is deprecated and will be removed in version 21.9. You should change your Blueprint instance to use instance.ctx.auth instead.

exists on line 241 and 263 in the file "initialization.py"
self.instance.auth = self.authentication_class(self.app, config=config)
self.instance.auth._extra_verifications = self.kwargs.get( "extra_verifications" )

**Comment by ahopkins** [comment]
See #209. I'll leave this open for now. Release is coming, you can ignore that though for now.
