### ISSUE TITLE
Protect class based views?

### ISSUE THREAD

**Issue by stefanm8** [ahopkins/sanic-jwt#26]
I'm not sure if you can protect the views with the existing decorator, I tried using it and it throws an error:
`   is_authorized = request.app.auth.is_authenticated(request, *args, **kwargs)
AttributeError: 'ClassBasedView' object has no attribute 'app'`

**Comment by ahopkins** [comment]
You are right.

The code for the `@protected()` decorator is pretty much verbatim from the [Sanic docs](http://sanic.readthedocs.io/en/latest/sanic/decorators.html). However, it does not seem to work in that incantation.

Funny, the exception I go was a different one.

Here is the CBVs that I used

```python
class PublicView(HTTPMethodView):
    def get(self, request):
        return json({"hello": "world"})


class ProtectedView(HTTPMethodView):
    decorators = [protected]

    def get(self, request):
        return json({"protected": True})


app.add_route(PublicView.as_view(), '/')
app.add_route(ProtectedView.as_view(), '/protected')
```

And the exception:

```
Traceback (most recent call last):
  File "./example/cbv.py", line 65, in <module>
    app.add_route(ProtectedView.as_view(), '/protected')
  File "/my/path/python3.5/site-packages/sanic/views.py", line 58, in as_view
    view = decorator(view)
TypeError: protected() takes 0 positional arguments but 1 was given
```

Even when I change the `protected` method to allow for intake of arguments:

```2017-11-14 00:43:44 - (sanic)[ERROR]: Invalid response object for url b'/protected', Expected Type: HTTPResponse, Actual Type: <class 'function'>
2017-11-14 00:43:44 - (sanic)[ERROR]: Traceback (most recent call last):
  File "/my/path/python3.5/site-packages/sanic/server.py", line 246, in write_response
    response.output(
AttributeError: 'function' object has no attribute 'output'
```

So, there is for sure some changes needed here to the decorator.

**Comment by ahopkins** [comment]
Checkout [this commit](https://github.com/ahopkins/sanic-jwt/commit/10230939769c211ed0a084435b5d1417f00ad8de) that I just pushed. It _seems_ to resolve the issue. It is a real quick Test that I wrote. 

Also, see [`./example/cbv.py`](https://github.com/ahopkins/sanic-jwt/blob/10230939769c211ed0a084435b5d1417f00ad8de/example/cbv.py#L57) for example usage. In particular, in the current usage, you will need to have your CBV methods marked as coroutines:

```python
class ProtectedView(HTTPMethodView):
    decorators = [protected]

    async def get(self, request):
        return json({"protected": True})
```

**Comment by stefanm8** [comment]
Calling the decorator seems to fix the issue on version sanic-jwt-0.3.1, with and without async 
`
decorators = [protected()]
`
Also using the code from the latest commit, everything works like a charm

**Comment by ahopkins** [comment]
Hmm ... we should look into that. You [should not need to call](http://sanic.readthedocs.io/en/latest/sanic/class_based_views.html#decorators) the decorator at the time the class is created.

**Comment by ahopkins** [comment]
In the next version to be released, this for sure passes all tests.

```python
class ProtectedView(HTTPMethodView):
    decorators = [protected]

    async def get(self, request):
        return json({"protected": True})
```
