### ISSUE TITLE
Newbie doc question

### ISSUE THREAD

**Issue by nhi-vanye** [ahopkins/sanic-jwt#38]
I'm trying to add authentication to a basic web app and its unclear how this works in the real world.

The flow that I'd like is

/index.html has the main application logic. This needs to be protected, but I'd like to redirect over to /login.html if no auth headers are present - to other username/password perform authentication and then redirect back to index.html.  

But as soon as I mark the blueprint handler for 'index.html' as @protected, the exceptions are thrown that there is no authentication header present - thats down in the sanic_jwt library so I don't get to intercept it.

What am I missing ?

Is there a better/more sanic_jwt to accomplish the task ? I think I'm missing the bigger picture on how to tie the various pieces (public, protected) together...

I guess the 'issue' is that the example could cover a transition case.

Thanks

richard

**Comment by ahopkins** [comment]
Thanks for posing the question.

You are right, there is 100% a lack in decent documentation and examples. Hopefully once we get past the first of the year I plan to dedicate a chunk of time to this. One thing for sure is upgrading the docs.

Checkout issues #13 and #14. They both are revolving around the same basic issue, and there is a plan to extend the functionality to customize how the application handles invalid authentications.

Now, to understand more to your point, are you trying to use this to protect an HTML endpoint? I suppose you could if using the cookie as opposed to header. But, like you point out in your question, how to handle the exception?

I really was thinking of this package to be used more for protecting REST API endpoints. Perhaps it also could do HTML responses.

One thing that may work is to add [middleware](http://sanic.readthedocs.io/en/latest/sanic/middleware.html#modifying-the-request-or-response) and look for the response status thrown by the exception handler.

```python
@app.middleware('response')
async def check_authentication(request, response):
    if response.status in [400, 401]:
        response.redirect('/login.html')
```

I have not tested the above.
