### ISSUE TITLE
User specific secrets

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#4]
https://github.com/ahopkins/sanic-jwt/blob/05310d9a3274ef810403eeb56243c60e1eaa084f/sanic_jwt/authentication.py#L68

**Comment by ahopkins** [comment]
There would ideally be a handler similar to the handlers (see `./handlers.py` and `./settings.py`) that are already implemented.

**Comment by terrycain** [comment]
My JWTs have a `kid` key ID in the header, would here be a good idea to (if configured) look for a key from a jwt key set? https://tools.ietf.org/html/rfc7517#section-5

So e.g.
I try and use a token with kid: test1, server doesnt know test1, so goes to https://example.org/jwk, that has a json dict with test1's public key in it, sanic-jwt then uses that as secret.

Does that make sense? Am happy to PR

**Comment by ahopkins** [comment]
@terrycain Thanks very much for taking the time and energy to figure this out. To be 100% honest, I am just returning from some time away, so I have not thoroughly reviewed the gist or the RFC. I will. But, nonetheless, here are my initial impressions.

1. Yes, a PR like this is definitely welcome.
1. To the extent possible, I would like to minimize the number of dependencies. Therefore, perhaps this would not be included by default, but would require a separate dependency `pip install sanic-jwt[something]`.
1. Another alternative, which was more along the lines of my initial thinking, the getting of the secret would be a handler that could easily be overridden. By default, it would just be an `async` method that is passed (for example) the `request`  object and returns the secret from the configurations. Then ... the user could override this with any custom method, including one that would go out and make another API call.
1. I have not specifically tested this, but using the new `get_<setting>()` methods from v1.1 ([see here](http://sanic-jwt.readthedocs.io/en/latest/pages/configuration.html#configuration-class)), this should be possible.

```python
class MyConfig(Configuration):

    def get_secret(self, request):
        return "some secret"

Initialize(
    app,
    configuration_class=MyConfig
```

The complication to this, and I need to take another look thru, is that I am not sure that the `getter` configurations take both awaitables and non-awaitables.

I'll try and put some more thought on this as well.

**Comment by ahopkins** [comment]
Closing. This will be in version 1.5

https://github.com/ahopkins/sanic-jwt/commit/d9930b784d5c9b851ea46733ed97664121be5ab5
