### ISSUE TITLE
Setting Scopes

### ISSUE THREAD

**Issue by python-programmer** [ahopkins/sanic-jwt#42]
hi, first of all, thank you for your awesome works
i have a model named scope and a another model named user.

User model:

```
User: 
    username
    password
    ...
```

Scope model:

```
Scope:
    name
    ...
```

User Scope Model
```

UserScope:
    user_id
    scope_id
```

where must I set the scopes in payload?

**Comment by ahopkins** [comment]
@python-programmer Thank you very much. There still is a lot of work I need to do to clean up the usage and documentation. And, I have some plans on how to make certain things more extendable for the developer.

As for your question ... you need to define a "handler" in the settings: `app.config.SANIC_JWT_HANDLER_PAYLOAD_SCOPES`

> Purpose: A handler method used to add scopes into a payload. It is a convenience method so that you do not need to extend the payload with the more verbose (yet, more flexible) SANIC_JWT_HANDLER_PAYLOAD_EXTEND. It should return either a string or a list of strings that meet the scope requirements. See the secion on Scopes for more details. Also, to make it easier for the developer, the user instance that is returned by the authenticate method is passed in as a parameter as seen below.

Say you have `app/lib/auth/handlers.py`. Inside you would have a method like this:

```python
async def my_scope_extender(user, *args, **kwargs):
    return user.scopes
```

And then, you would wire it up by adding a setting

```python
SANIC_JWT_HANDLER_PAYLOAD_SCOPES = 'app/lib/auth/handlers.my_scope_extender'
```

Given your example, I would expect your `User` model to have a property that can return a list of strings, with each string being a different [scope](https://github.com/ahopkins/sanic-jwt#scopes).

Let me know if this helps.
