### ISSUE TITLE
Check init methods for awaitable

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#48]
Should run a check to make sure the following methods if implemented are awaitable:

`store_refresh_token`
`retrieve_user`
`retrieve_refresh_token`
`authenticate`

**Comment by vltr** [comment]
Perhaps [inspect.isawaitable](https://docs.python.org/3/library/inspect.html#inspect.isawaitable) ? I'm thinking about implement these features since my `retrieve_user` implementation is not quite async :sweat_smile:

**Comment by vltr** [comment]
On a second thought, this could lead people to choose either implement an async function or not ...

**Comment by ahopkins** [comment]
I thought about this too. The dynamic scoping method does this check and adjusts accordingly. I like it.

Want to add the PR?

**Comment by vltr** [comment]
Yeap! A PR is _almost_ there at this time, but I think I'll need more time to add test cases to it and increase coverage - avoiding issues like #47. During the week, maybe?

**Comment by ahopkins** [comment]
@vltr  You rock.

**Comment by vltr** [comment]
@ahopkins well, I kind of got myself into a problem (bug?) in here. Here's what happens: my `retrieve_user` method returns a custom class that has the `user_id` property (_for internal use only_) and a `to_dict` method so it plays nicely with the `/auth/me` endpoint. The problem I found was in the `/auth/refresh` endpoint where, after the `retrive_user` [method is called](https://github.com/ahopkins/sanic-jwt/blob/master/sanic_jwt/blueprint.py#L121), it still calls an [internal method](https://github.com/ahopkins/sanic-jwt/blob/master/sanic_jwt/authentication.py#L132-L137) from `authentication.py` that seeks for a `dict` or the given `user_id` key in the object (in my case, getting the internal `user_id` property instead of the `user_id` given in the `to_dict` method, which differs). I think that the `_get_user_id` method should look for the `to_dict` method or a `dict` instance, dropping the `getattr` method approach, since there could be objects without a "readable" `user_id` attribute at all :bomb:

**Comment by ahopkins** [comment]
```python
    def _get_user_id(self, user):
        if isinstance(user, dict) or hasattr(user, 'to_dict'):
            user_id = user.get(self.app.config.SANIC_JWT_USER_ID)
        else:
            user_id = getattr(user, self.app.config.SANIC_JWT_USER_ID)
        return user_id
```

Is this the proposal? Makes sense.

**Comment by vltr** [comment]
@ahopkins this is what I did for `_get_user_id`, I think it is "safer" regarding the description of the object that should be returned with the `authenticate` method:

```python
# in exceptions
@add_status_code(500)
class InvalidRetrieveUserObject(SanicJWTException):

    def __init__(
            self,
            message="The retrieve_user method should return either a dict or an object with a to_dict method."
    ):
        super().__init__(message)
```

```python
    def _get_user_id(self, user):
        if isinstance(user, dict):
            user_id = user.get(self.app.config.SANIC_JWT_USER_ID)
        elif hasattr(user, 'to_dict') and callable(user.to_dict):
            user_id = user.to_dict().get(self.app.config.SANIC_JWT_USER_ID)
        else:
            raise exceptions.InvalidRetrieveUserObject()
        return user_id
```

It works nicely and give me confidence to have a `user_id` property in my object without exposing it. It kinda follows the `/auth/me` endpoint code. What do you think?

**Comment by ahopkins** [comment]
Nice. I say let's roll with that. Only question is, since we are sort of adding flexibility for `callable` and `awaitable`, maybe add another `elif` if the code is async? I propose that as much as we can, we allow users the option the ability to make any function work async or non-async. Thoughts?

**Comment by vltr** [comment]
Good catch. I'll add it and commit to master or into a new branch?

**Comment by ahopkins** [comment]
Usually a might say branch. But we both agree on the code which is simple enough. so I say to master it is.

Adam Hopkins

**Comment by vltr** [comment]
Okay. I'll just test the `async` nature of it and when working, I'll push it. Let's hope it doesn't break anything ... I'll add some tests later on. Or perhaps I'll push the code with tests, it's better this way.

**Comment by vltr** [comment]
Woah, this gave me some extra work when I implemented an exception on the `User` test class inside an `user_id` property ... I had to change the `/auth/me` blueprint, some other test cases and also `handlers.py` to behave like `_get_user_id` ... But it has a lot of unit tests on top of this and a 1% increase coverage (well, given everything that have changed ...) and worked flawlessly with my already running application - I even recreated something similar to my scenario in one test case (`test_endpoints_async_methods.py`), so _I think_ this might work straightforward but there may be some side effects if the returned object from `authenticate` rely on the existence of a `user_id` property or attribute ...

**Comment by ahopkins** [comment]
The other question and item to handle is what happens if a developer decides not to return a user object? The authenticate method should also just be able to handle truthiness and return a boolean. I do not believe the package handles this well yet.

Adam Hopkins

**Comment by vltr** [comment]
Yeap, then we might have to change the docs for the `authenticate` method. For now, it's a `dict` or an object with a `to_dict` method to work ...But, given the nature of JWT itself, how would something other than data can return from `authenticate` to build the payload?

**Comment by ahopkins** [comment]
The developer can build the payload themselves and override with the payload handlers. In the new `Initialize` class I think this will be even easier.

**Comment by vltr** [comment]
Unless ... The `authenticate` method returns a `bool` and the user would be responsible for generating the payload ... But then we would have to check if the payload created have everything in place, too (like `SANIC_JWT_USER_ID`) and so on ... I really don't know the effort this would take, or if using [`abc`](https://docs.python.org/3/library/abc.html) wouldn't be easier ...

PS: I was finishing this comment when you sent your reply above, heh

**Comment by ahopkins** [comment]
> PS: I was finishing this comment when you sent your reply above, heh

Nice.

Well, maybe we stick to the user object requirement for now (on `authenticate` return). And if there is a need down the road, keep the idea open that we may want to tackle this.

**Comment by vltr** [comment]
> And if there is a need down the road, keep the idea open that we may want to tackle this.

Yeap. I think it kind of works out of the box the way it is now ... IMO if returning an object, then this object would need to be a subclass of a stub with the `to_dict` method ... But that is just a long thought ...

**Comment by ahopkins** [comment]
I think it is more elegant just to tell the developer that they need to provide the to_dict or__dict__ method than to give them a base class. This way we are not making any application design decisions.

Adam Hopkins

**Comment by vltr** [comment]
Agreed. I'm pursuing this because it was on the docs, so we can define this too on the docs ... The only problem would be that `__dict__` **can't** be `async`, only `to_dict` ...

**Comment by ahopkins** [comment]
Okay. I think I am fine with that.

**Comment by vltr** [comment]
Allright! This **will need** documentation. I created a label to this issue - and others following, if needed.

**Comment by ahopkins** [comment]
I have added a note for this into the new set of documents. Closing.
