### ISSUE TITLE
How do i mount /auth on subroute 

### ISSUE THREAD

**Issue by hjunaid** [ahopkins/sanic-jwt#51]
I would like to mount /auth at /api/auth route. I see no setting in blueprint to achieve this 

bp = Blueprint('auth_bp')

Is there a way to achieve this?

**Comment by hjunaid** [comment]
Found the solution by setting SANIC_JWT_URL_PREFIX.

**Comment by ahopkins** [comment]
I was just about to post. A new version of the docs is around the corner. I will make sure to be more explicit.
