### ISSUE TITLE
Thoughts on how to refresh

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#52]
Right now, you are required to send the access token and the refresh token. 

Why? Well, it seems like a good idea to facilitate the lookup of refresh tokens by knowing against which user you are *trying* to look up. It seems like another layer (albeit thin) of security. The alternative is to lookup the user by refresh token alone. 

In the current operation, there is **NO** verification of the JWT at this stage while refreshing, it is used ONLY to pass the payload and get the intended `user_id`.

I think this is probably the best method, but I am open to thoughts on whether this should change. Perhaps it could be configurable.

**Comment by vltr** [comment]
I think this is a good approach to tighten up security (by cross-reference the expired token payload and the refresh token given), but this can be optional to the refresh token methods implementation (adding all required arguments to make this work to `retrieve_refresh_token` (most probably) and / or `store_refresh_token`).

**Comment by nogaems** [comment]
@ahopkins So why can't we just use the same approach as for the auth token itself and simply issue refresh tokens coupled with  expiration time? This way the mechanism of refreshing is pretty much straightforward, you just assure that the refresh token user matches the user of the auth token. Yes, that would allow multiple re-issues using the same refresh token, but why is this a problem anyway? 
From my understanding, refresh tokens exist to fulfill the ability of a user to stay logged in *a bit longer* without re-logging. Storing plain text credentials is not secure, so we use refresh tokens. If it would have expiration time, maybe even somewhat bigger than for an auth token, but still could expire, it would solve the problem of infinite refreshes, but most importantly, there would be no need to store refresh tokens at all.
In my opinion, this is important because one of the killer features of JWT authentication machanism is that it is *stateless*, but the burden of storing refresh tokens is kind of killing this feature. Is there actually no way to implement it stateless? Am I getting something wrong?

**Comment by ahopkins** [comment]
Stateless v stateful is not an absolute. JWTs are stateless in that you do not keep track of session information. Regardless of whether you are storing refresh tokens or not. 

Storing refresh tokens: does it mean you need a DB? Of course. Does it mean your auth system is now stateful? That seems (to me) an entirely theoretical discussion, and the more on point question are what are the pratical benefits/detriments to doing so.

Self authentication is great. Agreed. Storing the refresh token, however, does give you the ability to revoke them. A refresh token of the sort you are referring to means that they are irrevocable (unless you change your secret). I am not saying that this is a bad solution, but in most cases I would not advocate for it.

With that said, if you would like to issue self-authenticating refresh tokens, you are welcome to do so, and `sanic-jwt` will allow for it.

[Can I have an expirable refresh token?](https://sanic-jwt.readthedocs.io/en/latest/pages/refreshtokens.html#can-i-have-an-expirable-refresh-token)

Here is a working example to get you started:

```python
from sanic import Sanic
from sanic_jwt import exceptions
from sanic_jwt import Initialize
import jwt


class User:
    def __init__(self, id, username, password):
        self.user_id = id
        self.username = username
        self.password = password

    def __repr__(self):
        return "User(id='{}')".format(self.user_id)

    def to_dict(self):
        return {"user_id": self.user_id, "username": self.username}


users = [User(1, "user1", "abcxyz"), User(2, "user2", "abcxyz")]

username_table = {u.username: u for u in users}
userid_table = {u.user_id: u for u in users}


async def authenticate(request, *args, **kwargs):
    username = request.json.get("username", None)
    password = request.json.get("password", None)

    if not username or not password:
        raise exceptions.AuthenticationFailed("Missing username or password.")

    user = username_table.get(username, None)
    if user is None:
        raise exceptions.AuthenticationFailed("User not found.")

    if password != user.password:
        raise exceptions.AuthenticationFailed("Password is incorrect.")

    return user


async def generate_refresh_token():
    app = Sanic.get_app("myapp")
    payload = {}
    with app.auth.override(expiration_delta=60 * 60 * 24):
        payload = await app.auth.add_claims(payload, None)
    secret = await app.auth._get_secret(payload=payload, encode=True)
    algorithm = app.auth._get_algorithm()
    access_token = jwt.encode(payload, secret, algorithm=algorithm)
    return access_token


async def retrieve_refresh_token(request, user_id):
    refresh_token = request.json["refresh_token"]
    if await app.auth.verify_token(refresh_token):
        return refresh_token
    return None


def store_refresh_token(*args, **kwargs):
    ...


def retrieve_user(request, payload):
    return userid_table.get(payload["user_id"])


app = Sanic("myapp")
Initialize(
    app,
    authenticate=authenticate,
    generate_refresh_token=generate_refresh_token,
    refresh_token_enabled=True,
    retrieve_user=retrieve_user,
    retrieve_refresh_token=retrieve_refresh_token,
    store_refresh_token=store_refresh_token,
)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8888, debug=True)
```
