### ISSUE TITLE
How to return json response on authenticate?

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#56]
Hi,
Sorry for this other question, bu i used the authenticate function provided in the example.

How modify the authenticate response to return something like this (application/json):

```json
{"status": "incorrect_password"}
```
For example.

Thanks

**Comment by ahopkins** [comment]
There is no way to customize the output right now, unless you were to override the blueprint.

With that said:

1) I am working actively on a new release that will include this feature;
2) You could just add an [exception handler](http://sanic.readthedocs.io/en/latest/sanic/exceptions.html#handling-exceptions)

```python
@app.exception(exceptions.AuthenticationFailed)
def exception_response(request, exception):
    return response.text(str(exception), status=exception.status_code)
```

**Comment by gbnk0** [comment]
Nice thanks for your reply
