### ISSUE TITLE
Check backwards compatibility

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#64]
Check if everything is working using `initialize` or `Initialize`, duplicating (or scrambling) some of the unit tests. _Perhaps_ give some special attention to `scopes` ?

**Comment by ahopkins** [comment]
I am comfortable with the level of backwards compatibility. There seems to be one big exception: handlers.

Previously, there were a few handler methods that could be used (for example) to extend functionality like building the payload, or retrieving scopes. This could be done by providing the import path to the method.

This has been removed in favor of subclassing the objects, or in case of scopes: `initialize(add_scopes_to_payload=something)`.

I am okay with this breaking change and have handled it by providing the developer an exception if the upgrade and are using `SANIC_JWT_HANDLER_PAYLOAD_SCOPES`, `SANIC_JWT_PAYLOAD_HANDLER`, or `SANIC_JWT_HANDLER_PAYLOAD_EXTEND`.

**Comment by vltr** [comment]
Oh, now I get the #67 idea. This would be something to think about ... But, just for curiosity: I upgraded my app to the proposed v1 in a matter of minutes, nothing fancy (from the last version provided on pypi).

**Comment by ahopkins** [comment]
Sounds good. It really should not be too hard to upgrade assuming we did our job right. I think the critical thing accomplished was adding a much deeper level of control.

**Comment by vltr** [comment]
> I think the critical thing accomplished was adding a much deeper level of control.

Yeap, there are a lot of new features (mostly requested); things _to be implemented_ by developers in their apps in v1, so migration will be more like adding control over solving broken functionality ... :wink:
