### ISSUE TITLE
Decorators on Initialize instance

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#68]
In v1, decorators are in their own module.

```python
from sanic_jwt.decorators import protected, scoped
```

In order to protect a route that was initialized on a `Blueprint`, you need to pass the instance.

```python
@protected(my_blueprint)
async def some_view(request, *args, **kwargs):
   ...
```

I would like to move away from this methodology, and instead have the decorator be a method on the `sanic_jwt.Initialize` instance. Why?

Well, for one thing, it is an easier syntax, with less likelihood that the developer will forget to pass the right instance.

```python
sanicjwt = Initialize(...)

@sanicjwt.protected
async def some_view(request, *args, **kwargs):
   ...
```

But, an even better solution is that it could be used to really localize configuration for a single endpoint. Perhaps, even at run time.

```python
sanicjwt = Initialize(expiration_delta=60)

@sanicjwt.protected(expiration_delta=20)
async def some_view(request, *args, **kwargs):
   ...

@sanicjwt.protected(expiration_delta=lambda: 5)
async def some_other_view(request, *args, **kwargs):
   ...
```

**Comment by vltr** [comment]
@ahopkins that was mindblowing. The level of decoupling and granularity of this would be a killer!

**Comment by vltr** [comment]
Related to decorators, there's also #87. I could tackle it, but I think it is more important to see #70 first - since it would provide a lot of changes to the code.

**Comment by ahopkins** [comment]
Verified that this is done, and documentation added.
