### ISSUE TITLE
authenticate must return object or dict, not bool

### ISSUE THREAD

**Issue by kerma** [ahopkins/sanic-jwt#7]
Docs lie a bit. `autheticate` must return object with (default) `user_id` attribute or dict that has `user_id` key set. Otherwise all hell breaks loose and nothing works. 

Minimum workable example would probably be:

    def authenticate():
        return dict(user_id='user_1')

**Comment by ahopkins** [comment]
Thanks @kerma for catching that. You are right. The `authenticate` method is meant to return a "user" object. Whatever that may be for your application. That part of the documentation was a relic from an earlier version that did not require that. 

Do you have a particular reason for *not* wanting to return an object?

If you could be so kind to submit a PR to fix the docs, that would be awesome.

**Comment by kerma** [comment]
@ahopkins Created a PR. I have no reason not to return an object there. I just copy-pasted the minimum example to test it out and it didn't work (:

**Comment by ahopkins** [comment]
@kerma Thanks.
