### ISSUE TITLE
class_based_views doesn't work for me v1.0

### ISSUE THREAD

**Issue by gbnk0** [ahopkins/sanic-jwt#75]
I tried to add class_based_views, like in the documentation:

```python
class MyEndpoint(BaseEndpoint):

    def test(self):
        return True

my_views = (
    ('/tests', MyEndpoint)
)


initialize(app, class_based_views=my_views)

```
I get a 404. Misconfiguration made by me or bug?

**Comment by gbnk0** [comment]
I also tried with the /register exmaple

**Comment by gbnk0** [comment]
ok, i understand, "class_based_views" is only present in the documentation but not in the sanic_jwt code

**Comment by ahopkins** [comment]
This is a mistake on my part. `class_based_views` in the documentation should read `class_views`.

**Comment by ahopkins** [comment]
Look at [test_endpoints_extra.py](https://github.com/ahopkins/sanic-jwt/blob/dev/tests/test_endpoints_extra.py) for an example.

**Comment by ahopkins** [comment]
Docs have been updated.

![image](https://user-images.githubusercontent.com/166269/36640983-4d37f6cc-1a31-11e8-8ed3-5b93728f33d7.png)
