### ISSUE TITLE
Access User Detail in protected routes

### ISSUE THREAD

**Issue by jaymalik217** [ahopkins/sanic-jwt#87]
Is there a way to inject user in protected routes? Something like this?

```
@auth_bp.post("delete_account")
@protected()
async def delete_account(request):
    email = request['user]['email'] #access user details from request object
    logger.info("Deleting Account for {}".format(email))
    resp = auth_service.delete_account(email)
    return resp
```

**Comment by ahopkins** [comment]
Hmm, from the Initialize object, this could be possible in the current version. I'll post a code samples later today.

However, this seems, like a potentially good idea to make it off the request object as proposed. We may need to think thru how and when to do such an injection. On all protected requests? Or, just a callable that is retrieved on request? Should it be the user object, or just the id?

**Comment by ahopkins** [comment]
Although not the same issue #81 is related.

**Comment by ahopkins** [comment]
The downside that I see would be that every request would incur the DB overhead. In general, the user object is retrieved when building the payload on the authentication, and by the retrieve user endpoint.

**Comment by gbnk0** [comment]
I do this in a middleware

**Comment by ahopkins** [comment]
@gbnk0 Do you mind  posting the snippet? Is it utilizing the same retrieve_user awaitable.

**Comment by gbnk0** [comment]
It's very dirty for my database, i just do a retrieve user each time and i put the user in the request. So i can access the user object on each protected route

**Comment by gbnk0** [comment]
The snippet: 
```python

@app.middleware('request')
async def add_start_time_1(request):
    request['start_time'] = datetime.now()

    apmclient.begin_transaction('processors')

    if 'authorization' in request.headers.keys():
        user = get_user(request)
        if user:
            request['user'] = user
```

**Comment by gbnk0** [comment]
And the get_user(request) is in fact a call to retrieve_user ( dirty code i know... )

**Comment by ahopkins** [comment]
I'm thinking (without the benefit of looking at the code right now while I'm on my phone) that maybe the way would be to make it an option to inject via configuration, and also the @protected decorator. This has the benefit of allowing it to continue be utilized on both an app and a Blueprint. Doing it as blanket Middleware might not make sense if the authentication was ONLY used in a per blueprint level.

    @protected(inject_user=True)

or

    Initialize(app, inject_user=True)

The other would be to inject the method ALL the time.

    await request.retrieve_user()

But, under the hood, the package allows the method to be a callable or an awaitable. It might get a little more confusing and messy than the first one.

**Comment by jaymalik217** [comment]
As an interim solution, i am using this to get user id from payload ...
```

def extract_email(request):
    payload = request.app.auth.verify(request, return_payload=True)
    return payload['email'] if payload else None

```

**Comment by gbnk0** [comment]
You're right, the inject_user=True is exactly what i needed and i think it's rhe same for @jaymalik217.

**Comment by ahopkins** [comment]
@jaymalik217 Also, if you are usually not using it app wide, you can also get to the endpoint 

    request.app.auth.retrieve_user()

For example 

    payload = self.instance.auth.extract_payload(request)
    user = await utils.call(
        self.instance.auth.retrieve_user, request, payload)

**Comment by vltr** [comment]
> I'm thinking (...) that maybe the way would be to make it an option to inject via configuration, and also the `@protected` decorator

The `inject_user=True` would be awesome. In my case, I'm associating a sort of "context" object to every request (using middlewares) to lazy evaluate the if a user is present or not - with associate methods for some other functionalities. It does work well, but the inject idea is very nice.

**Comment by ahopkins** [comment]
What does everyone think: kwarg or a second decorator?

    @protected(inject_user=True)

or

    @protected 
    @inject_user

My hesitancy with the first is that it potentially makes a lot of arguments on the scoped decorator.

**Comment by Garito** [comment]
I would like to go for @inject_user decorator for that matter

**Comment by Garito** [comment]
I don't understand your first paragraf (is there any difference for a decorator if is app or bp?)

The more reuse of previous actions the better but I don't get how you will reuse the /auth/me (which would be supernice)

**Comment by ahopkins** [comment]
@vltr That was sort of my thought. There would be a config that defaults to `False`

    SANIC_JWT_ALWAYS_INJECT_USER = False

Which, then could be switched on:

```python
Initialize(app, always_inject_user=True)

@app.route("/protected")
@protected()
async def protected(request):
    return json(request.user.to_dict())
```

Or, if it is off, then the same would be available with a decorator:


```python
Initialize(app)

@app.route("/protected")
@protected()
@inject_user()
async def protected(request):
    return json(request.user.to_dict())
```

**Comment by ahopkins** [comment]
@Garito 

Currently, the decorator stands on its own. Therefore if you want to use with a `bp`, you need to explicitly [pass the instance into the decorator](http://sanic-jwt.readthedocs.io/en/latest/pages/protected.html#the-protected-decorator):

```python
bp = Blueprint('Users')
Initialize(bp)

@bp.get('/users/<id>')
@protected(bp)
async def users(request, id):
    ...
```

Therefore, in order to make the `inject_user` decorator work as @vltr expects, it also would need to take that `bp` instance as an argument.

However in #68, I am wanting to make it possible to have the decorator be a method off the `sanic_jwt.Initialize` instance so that you would not need to do that.

```python
sanicjwt = Initialize(expiration_delta=60)

@sanicjwt.protected(expiration_delta=20)
@sanicjwt.inject_user()
async def some_view(request, *args, **kwargs):
   ...

**Comment by Garito** [comment]
Got it, thanks!

**Comment by vltr** [comment]
@Garito I think @ahopkins made most of the explanation, but just to clear things out: you can create more than one instance of `sanic-jwt` inside your project, either a project-wide instance (using `app` as an argument`) or for just a piece of your application, like a blueprint - hence you can have one, two, three different configurations inside one running app. For me, this is awesome since I can leverage configurations between internal endpoints (consumable from my clients) and public endpoints, that must have a hardened security upon and etc :wink:

**Comment by vltr** [comment]
Oh, and @Garito, the `/auth/me` endpoint returns the payload of the current user, which is what we want (correct me if I'm wrong). I wouldn't like to provide extra methods to access the database and return a custom user object to inject into `request`, leaving this logic to the developer (but I'm open to a custom hook, @ahopkins to advocate on this). Since `/auth/me` already brings all the information needed, no need to go further into the implementation - unless the hook idea seems valid.

**Comment by ahopkins** [comment]
@vltr Not sure another hook besides `retrieve_user` is needed. Anything more might just be confusing. With that said ... I am working on identifying all the hook locations I can to allow developers some more flexibility.

**Comment by vltr** [comment]
Oh, I completely forgot that function. No hooks needed, then! :smile:

**Comment by ahopkins** [comment]
I added the `inject_user` decorator. All it does is call `retrieve_user` behind the scenes and stick the result of that into the keyword args for your endpoint.

```python
@sanic_app.route("/protected/user")
    @sanic_jwt.inject_user()
    @sanic_jwt.protected()
    async def my_protected_user(request, user):
        return json({
            'user_id': user.user_id
        })
```
