### ISSUE TITLE
Decoupling for microservice architectures

### ISSUE THREAD

**Issue by ahopkins** [ahopkins/sanic-jwt#90]
Currently, the `sanic-jwt` model is not ideal for microservice architecture. The module requires that it be able to `authenticate` a user and that has the `/auth` endpoints setup. However, in a microservice setup, likely there will only be one service that needs this functionality. The rest would need to have only the `@protected` and `@scoped` decorators.

Therefore, we should introduce a new configuration to enable this. Something like this:

```python
Initialize(app, auth_mode=False)
```

If `auth_mode` is **off**, I do not get an error for forgetting to pass `authenticate`.

    sanic_jwt.exceptions.AuthenticateNotImplemented: Sanic JWT initialized without providing an authenticate method.

And, it does not instantiate the blueprint, so that instance does not get any of the `/auth` endpoints.

**Comment by vltr** [comment]
Neat :+1:
