### ISSUE TITLE
InvalidRetrieveUserObject following the documentation

### ISSUE THREAD

**Issue by Pac0o** [ahopkins/sanic-jwt#91]
Hi, I was trying this plugin and following the instrucctions on the [Simple Usage section ](http://sanic-jwt.readthedocs.io/en/latest/pages/simpleusage.html) and after making the correct call that should return an access token instead I got an InvalidRetrieveUserObject exception
![image](https://user-images.githubusercontent.com/16431439/38391242-1815185c-38fa-11e8-960a-0393fffcb84c.png)

I was able to resolve this implementing a to_dict method in the User class
![image](https://user-images.githubusercontent.com/16431439/38391411-870d8424-38fa-11e8-894e-52c989aa1d52.png)

Is the documentation outdated or it's me doing something wrong?

Regards

**Comment by vltr** [comment]
Thanks, @Pac0o ! That is indeed a problem in the docs. I already spotted it and will be updated with v1.1 :+1:
