### ISSUE TITLE
Test subclasses on initialize

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#92]
Test all provided classes inside `Initialize`

**Comment by ahopkins** [comment]
Test them for what? That they are subclasses appropriately?

**Comment by vltr** [comment]
Yeap. In fact, this is something already done - there were some bits here and there validating `Authentication`, `Configuration` and etc already and all I did was put these validations inside `Initialize`. I just created this issue to keep record :wink:
