### ISSUE TITLE
Format code using black

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#94]
Format the source code of `sanic-jwt` using [`black`](https://github.com/ambv/black), adding to `Makefile`.

**Comment by vltr** [comment]
Had to add `W503` to `pep8ignore` in `pytest.ini`

**Comment by ahopkins** [comment]
`black` is actively violating W503?

**Comment by vltr** [comment]
It looks like :-/



Em sáb, 14 de abr de 2018 18:33, Adam Hopkins <notifications@github.com>
escreveu:

**Comment by vltr** [comment]
Should we, well, report it?

**Comment by ahopkins** [comment]
I think so.

**Comment by vltr** [comment]
Another user [have filled an issue](https://github.com/ambv/black/issues/113) about this.

**Comment by vltr** [comment]
For now I disabled `W503`, but we might enabled it again, add the necessary parenthesis or wait for a newer version of `black` to do so.

**Comment by ahopkins** [comment]
Closing. Black is in the new `makefile`. Maybe we will reopen a new ticket to automate on commit. No need for that now though.
