### ISSUE TITLE
Override / Implement your own endpoints

### ISSUE THREAD

**Issue by vltr** [ahopkins/sanic-jwt#97]
Enable developers to implement their own endpoints (like `/auth`, `/auth/me`, `/auth/verify`, etc) if they want by subclassing `BaseEndpoint` ...

```python
class MyAuthenticateEndpoint(BaseEndpoint):

    async def post(self, request, *args, **kwargs):
        # do your override here
        return json(my_return)
```

... and inserting into `Initialize` as kwargs:

```python
app = Sanic()
Initialize(
    app,
    authenticate_endpoint=MyAuthenticateEndpoint)
```

Or adding into a `Configuration` subclass:

```
class MyConfig(Configuration):
    authenticate_endpoint = MyAuthenticateEndpoint

app = Sanic()
Initialize(app, configuration_class=MyConfig)
```

Remembering, there endpoints *should* subclass `BaseEndpoint`.

**Comment by ahopkins** [comment]
Hmmm ... Not sure about this. I sort of liked the alternative approach that we talked about that basically allowed you to turn endpoints on and off. There already is a mechanism to add custom endpoints. I am not sure we need to remap the existing endpoints. Perhaps just disable them ...

Or, perhaps the solution is that the config value is set to `None` instead of `auth`. If the default endpoints do not have a path in the config, don't attach.

**Comment by ahopkins** [comment]
Please don't get me wrong. It looks like a nice solution. Part of my hesitancy with this feature implemented like this, however, is that now there are two different ways to add endpoints depending upon whether or not you are trying to "replace" or "reuse" one of the existing functionalities/paths

```python
        Initialize(
            app,
            authenticate_endpoint=MyAythenticationEndpoint,
            authenticate=lambda: True,
        )
```

and

```python
my_views = (
    ('/register', Register),
)

Initialize(app, class_views=my_views)
```

---

I would sort of just prefer:

```
my_views = (
    ('/auth', MyCustomAuth),
)

Initialize(app, class_views=my_views)
```

be identical to:


```
my_views = (
    ('/mycustomauth', MyCustomAuth),
)

Initialize(app, class_views=my_views, path_to_authenticate=None)
```

**Comment by vltr** [comment]
Or if I leave `auth_mode=False` with some of the tweaks I made today, then `class_views` would work perfectly for this. The _only_ problem would be to set all endpoints manually, but that's not a huge task since it's only four :wink:

**Comment by ahopkins** [comment]
Closing this since it seems to be working and provides a way to accomplish this.
