### ISSUE TITLE
Latest vs Dev Documents missing to_dict in Examples

### ISSUE THREAD

**Issue by c-goosen** [ahopkins/sanic-jwt#98]
Dev documentation is correct, but latest http://sanic-jwt.readthedocs.io/en/latest/pages/simpleusage.html is missing to_dict in the one example.

Could add a upgrade section on future big changes like this.

**Comment by vltr** [comment]
Thanks, @c-goosen ! The docs are being reviewed prior to the 1.1 release. We are aware of these changes and the docs will be given an special care :wink:

**Comment by c-goosen** [comment]
Perfect. Was going to do a pull request, then I realised the two are just out of sync. Will keep an eye out for it.

**Comment by vltr** [comment]
I really appreciate your effort, @c-goosen ! :beers:

**Comment by ahopkins** [comment]
This is in the documentation that is being prepped for release.

**Comment by c-goosen** [comment]
Thanks!

Christo Goosen - CTO
--------------------------------
Personal Account

Other contact details:
work: christo.goosen@takectrl.co.za
owasp: christo.goosen@owasp.org
bsides: christo@bsidescapetown.co.za
gmail: christogoosen@gmail.com
Linkedin: https://www.linkedin.com/in/christo-goosen-ctrl
github: c-goosen
website: http://www.christogoosen.co.za


PGP: BD8A 96B6 8FC4 935E 4735  3D33 5CAB 8762 1A75 F1F2

**Comment by ahopkins** [comment]
🍻 Getting 1.1 prepped for release next week. There will be some more examples and helpful suggestions in the docs for anyone that needs to dig deeper with more control.
